<?php
$country_list = array(
	"Afghanistan",
	"Aland Islands",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia",
	"Bosnia",
	"Botswana",
	"Brazil",
	"British Virgin Islands",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cape Verde",
	"Cayman Islands",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo Brazzaville",
	"Congo Kinshasa",
	"Cook Islands",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Curacao",
	"Cyprus",
	"Czech Republic",
	"Cote Ivoire",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Ethiopia",
	"Faroe Islands",
	"Figi",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran Republic",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea Republic",
	"Kuwait",
	"Kyrgyzstan",
	"Lao",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Macedonia",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maladives",
	"Mali",
	"Marshall Islands",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestinian",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Reunion",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saint Barthelemy",
	"Saint Helena",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint-Martin",
	"Saint Pierre and Miquelon",
	"Saint Vincent and The Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Sint Maarten",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Swaziland",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela",
	"Vietnam",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
);

$regions_list = array(
	"Afghanistan"=> array(
		"Badakhshan",
		"Badghis",
		"Baghlan",
		"Balkh",
		"Bamian",
		"Daykondi",
		"Farah",
		"Faryab",
		"Ghazni",
		"Ghowr",
		"Helmand",
		"Herat",
		"Jowzjan",
		"Kabol",
		"Kandahar",
		"Kapisa",
		"Khowst",
		"Konar",
		"Kondoz",
		"Laghman",
		"Lowgar",
		"Nangarhar",
		"Nimruz",
		"Nurestan",
		"Oruzgan",
		"Paktia",
		"Paktika",
		"Panjshir",
		"Parvan",
		"Samangan",
		"Sar-e Pol",
		"Takhar",
		"Vardak",
		"Zabol",
	),
	"Aland Islands"=> array(
		"Appelo",
		"Bergo",
		"Boxo",
		"Dano",
		"Degero",
		"Eckero",
		"Finbo",
		"Foglo",
		"Kumlinge",
		"Lappo",
		"Lemland",
		"Loko",
		"Lumparland",
		"Noto",
		"Ostersocknen",
		"Saggo",
		"Sglinge",
		"Simskala",
		"Sommaron",
		"Storsottunga",
		"Vardo",
	),
	"Albania"=> array(
		"Berat",
		"Diber",
		"Durres",
		"Elbasan",
		"Fier",
		"Gjirokaster",
		"Korce",
		"Kukes",
		"Lezhe",
		"Shkoder",
		"Tirane",
		"Vlore",
	),
	"Algeria"=> array(
		"Adrar",
		"Ain Defla",
		"Ain Temouchent",
		"Alger",
		"Annaba",
		"Batna",
		"Bechar",
		"Bejaia",
		"Biskra",
		"Blida",
		"Bordj Bou Arreridj",
		"Bouira",
		"Boumerdes",
		"Chlef",
		"Constantine",
		"Djelfa",
		"El Bayadh",
		"El Oued",
		"El Tarf",
		"Ghardaia",
		"Guelma",
		"Illizi",
		"Khenchela",
		"Laghouat",
		"M sila",
		"Mascara",
		"Medea",
		"Mila",
		"Mostaganem",
		"Naama",
		"Oran",
		"Ouargla",
		"Oum el Bouaghi",
		"Relizane",
		"Saida",
		"Setif",
		"Sidi Bel Abbes",
		"Skikda",
		"Souk Ahras",
		"Tamanghasset",
		"Tebessa",
		"Tiaret",
		"Tindouf",
		"Tipaza",
		"Tissemsilt",
		"Tizi Ouzou",
		"Tlemcen",
	),
	"American Samoa"=> array(
		"Eastern District",
		"Western District",
	),
	"Andorra"=> array(
		"Eastern District",
		"Western DistrictCanillo",
		"Encamp",
		"Escaldes-Engordany",
		"La Massana",
		"Ordino",
		"Sant Julia de Loria",
	),
	"Angola"=> array(
		"Bengo",
		"Benguela",
		"Bie",
		"Cabinda",
		"Cuando Cubango",
		"Cuanza Norte",
		"Cuanza Sul",
		"Cunene",
		"Huambo",
		"Huila",
		"Luanda",
		"Lunda Norte",
		"Lunda Sul",
		"Malanje",
		"Moxico",
		"Namibe",
		"Uige",
		"Zaire",
	),
	"Anguilla"=> array(
		"Blowing Point",
		"Dog Island",
		"Little Scrub Island",
		"Pricky Pear Cays",
		"Sandy Island",
		"Sandy Ground Village",
		"Scrub Island",
		"The Valley",
		"West End",
	),
	"Antarctica"=> array(
		"Antarctica",
	),
	"Antigua and Barbuda"=> array(
		"Antigua and Barbuda",
	),
	"Argentina"=> array(
		"Buenos Aires",
		"Catamarca",
		"Chaco",
		"Chubut",
		"Cordoba",
		"Corrientes",
		"Distrito Federal",
		"Entre Rios",
		"Formosa",
		"Jujuy",
		"La Pampa",
		"La Rioja",
		"Mendoza",
		"Misiones",
		"Neuquen",
		"Rio Negro",
		"Salta",
		"San Juan",
		"San Luis",
		"Santa Cruz",
		"Santa Fe",
		"Santiago del Estero",
		"Tierra del Fuego",
		"Tucuman",
	),
	"Armenia"=> array(
		"Aragatsotn",
		"Ararat",
		"Armavir",
		"Gegharkunik",
		"Kotayk",
		"Lori",
		"Shirak",
		"Syunik",
		"Tavush",
		"Vayots Dzor",
		"Yerevan",
	),
	"Aruba"=> array(
		"Noord",
		"Tanki Leendert",
		"Oranjestad West",
		"Oranjestad Oost",
		"Paradera",
		"San Nicolas Noord",
		"San Nicolas Zuid",
		"Santa Cruz",
		"Savaneta",
		"Total Aruba",
	),
	"Australia"=> array(
		"Australian Capital Territory",
		"New South Wales",
		"Northern Territory",
		"Queensland",
		"South Australia",
		"Tasmania",
		"Victoria",
		"Western Australia",
	),
	"Austria"=> array(
		"Burgenland",
		"Karnten",
		"Niederosterreich",
		"Oberosterreich",
		"Salzburg",
		"Steiermark",
		"Tirol",
		"Vorarlberg",
		"Wien",
	),
	"Azerbaijan"=> array(
		"Abseron",
		"Agcabadi",
		"Agdam",
		"Agdas",
		"Agstafa",
		"Agsu",
		"Ali Bayramli",
		"Astara",
		"Baki",
		"Balakan",
		"Barda",
		"Beylaqan",
		"Bilasuvar",
		"Cabrayil",
		"Calilabad",
		"Daskasan",
		"Fuzuli",
		"Gadabay",
		"Ganca",
		"Goranboy",
		"Goycay",
		"Haciqabul",
		"Imisli",
		"Ismayilli",
		"Kalbacar",
		"Lacin",
		"Lankaran",
		"Lerik",
		"Masalli",
		"Mingacevir",
		"Naftalan",
		"Naxcivan",
		"Neftcala",
		"Oguz",
		"Qabala",
		"Qax",
		"Qazax",
		"Qobustan",
		"Quba",
		"Qubadli",
		"Qusar",
		"Saatli",
		"Sabirabad",
		"Saki",
		"Salyan",
		"Samaxi",
		"Samkir",
		"Samux",
		"Sumqayit",
		"Susa",
		"Tartar",
		"Tovuz",
		"Ucar",
		"Xacmaz",
		"Xankandi",
		"Xanlar",
		"Xizi",
		"Xocali",
		"Xocavand",
		"Yardimli",
		"Yevlax",
		"Zangilan",
		"Zaqatala",
		"Zardab",
	),
	"Bahamas"=> array(
		"Freeport",
		"Fresh Creek",
		"Harbour Island",
		"High Rock",
		"Long Island",
		"Marsh Harbour",
		"New Providence",
		"Rock Sound",
	),
	"Bahrain"=> array(
		"Al Hidd",
		"Manama",
		"Western Region",
		"Central Region",
		"Northern Region",
		"Muharraq",
		"Rifa and Southern Region",
		"Jidd Haffs",
		"Isa Town",
		"Hawar Islands",
		"Sitra",
	),
	"Bangladesh"=> array(
		"Barisal",
		"Chittagong",
		"Dhaka",
		"Khulna",
		"Rajshahi",
		"Rangpur",
		"Sylhet",
	),
	"Barbados"=> array(
		"Christ Church",
		"Saint Andrew",
		"Saint George",
		"Saint James",
		"Saint John",
		"Saint Joseph",
		"Saint Lucy",
		"Saint Michael",
		"Saint Peter",
		"Saint Philip",
		"Saint Thomas",
	),
	"Belarus"=> array(
		"Brest",
		"Homel",
		"Hrodna",
		"Magileu",
		"Minsk",
		"Vitebsk",
	),
	"Belgium"=> array(
		"Antwerpen",
		"Henegouwen",
		"Luik",
		"Limburg",
		"Luxemburg",
		"Namen",
		"Oost-Vlaanderen",
		"Vlaams-Brabant",
		"Waals-Brabant",
		"West-Vlaanderen",
	),
	"Belize"=> array(
		"Belize",
		"Cayo",
		"Corozal",
		"Orange Walk",
		"Stann Creek",
		"Toledo",
	),
	"Benin"=> array(
		"Alibori",
		"Atakora",
		"Atlantique",
		"Borgou",
		"Collines",
		"Donga",
		"Kouffo",
		"Littoral",
		"Mono",
		"Oueme",
		"Plateau",
		"Zou",
	),
	"Bermuda"=> array(
		"Devonshire",
		"Hamilton",
		"Pembroke",
		"Sandys",
		"Smiths",
		"Southampton",
		"st Georges",
	),
	"Bhutan"=> array(
		"Bumthang",
		"Chukha",
		"Dagana",
		"Gasa",
		"Haa",
		"Lhuntse",
		"Mongar",
		"Paro",
		"Pemagatshel",
		"Punakha",
		"Samdrup Jongkhar",
		"Samtse",
		"Sarpang",
		"Thimphu",
		"Trashigang",
		"Trashiyangtse",
		"Trongsa",
		"Tsirang",
		"Wangdue Phodrang",
		"Zhemgang",
	),
	"Bolivia"=> array(
		"Chuquisaca",
		"Cochabamba",
		"El Beni",
		"La Paz",
		"Oruro",
		"Pando",
		"Potosi",
		"Santa Cruz",
		"Tarija",
	),
	"Bosnia"=> array(
		"Bosanska krajina",
		"Central Bosnia",
		"Herzegovina",
		"North",
		"Posavina",
		"Sarajevo",
	),
	"Botswana"=> array(
		"Central",
		"Ghanzi",
		"Kgalagadi",
		"Kgatleng",
		"Kweneng",
		"North-East",
		"North-West",
		"South-East",
		"Southern",
	),
	"Brazil"=> array(
		"Acre",
		"Alagoas",
		"Amapa",
		"Amazonas",
		"Bahia",
		"Ceara",
		"Distrito Federal",
		"Espirito Santo",
		"Goias",
		"Maranhao",
		"Mato Grosso",
		"Mato Grosso do Sul",
		"Minas Gerais",
		"Para",
		"Paraiba",
		"Parana",
		"Pernambuco",
		"Piaui",
		"Rio Grande do Norte",
		"Rio Grande do Sul",
		"Rio de Janeiro",
		"Rondonia",
		"Roraima",
		"Santa Catarina",
		"Sao Paulo",
		"Sergipe",
		"Tocantins",
	),
	"British Virgin Islands"=> array(
		"Anegada",
		"Jost Van Dyke",
		"Road Town",
		"Spanish Town",
		"Tortola",
		"The Settlement",
		"Virgin Gorda",
	),
	"Brunei"=> array(
		"Belait",
		"Brunei and Muara",
		"Temburong",
		"Tutong",
	),
	"Bulgaria"=> array(
		"Blagoevgrad",
		"Burgas",
		"Dobrich",
		"Gabrovo",
		"Grad Sofiya",
		"Khaskovo",
		"Kurdzhali",
		"Kyustendil",
		"Lovech",
		"Montana",
		"Pazardzhik",
		"Pernik",
		"Pleven",
		"Plovdiv",
		"Razgrad",
		"Ruse",
		"Shumen",
		"Silistra",
		"Sliven",
		"Smolyan",
		"Sofiya",
		"Stara Zagora",
		"Turgovishte",
		"Varna",
		"Veliko Turnovo",
		"Vidin",
		"Vratsa",
		"Yambol",
	),
	"Burkina Faso"=> array(
		"Bale",
		"Bam",
		"Banwa",
		"Bazega",
		"Bougouriba",
		"Boulgou",
		"Boulkiemde",
		"Ganzourgou",
		"Gnagna",
		"Gourma",
		"Houet",
		"Ioba",
		"Kadiogo",
		"Kenedougou",
		"Komoe",
		"Komondjari",
		"Kompienga",
		"Kossi",
		"Koulpelogo",
		"Kouritenga",
		"Kourweogo",
		"Leraba",
		"Loroum",
		"Mouhoun",
		"Namentenga",
		"Naouri",
		"Nayala",
		"Noumbiel",
		"Oubritenga",
		"Oudalan",
		"Passore",
		"Poni",
		"Sanguie",
		"Sanmatenga",
		"Seno",
		"Sissili",
		"Soum",
		"Sourou",
		"Tapoa",
		"Tuy",
		"Yagha",
		"Yatenga",
		"Ziro",
		"Zondoma",
		"Zoundweogo",
	),
	"Burundi"=> array(
		"Bubanza",
		"Bujumbura Mairie",
		"Bujumbura Rural",
		"Bururi",
		"Cankuzo",
		"Cibitoke",
		"Gitega",
		"Karuzi",
		"Kayanza",
		"Kirundo",
		"Makamba",
		"Muramvya",
		"Muyinga",
		"Mwaro",
		"Ngozi",
		"Rutana",
		"Ruyigi",
	),
	"Cambodia"=> array(
		"Banteay Meanchey",
		"Battambang",
		"Kampong Cham",
		"Kampong Chhnang",
		"Kampong Speu",
		"Kampong Thom",
		"Kampot",
		"Kandal",
		"Kep",
		"Koh Kong",
		"Kratie",
		"Mondulkiri",
		"Oddar Meanchey",
		"Pailin",
		"Phnom Penh",
		"Preah Sihanouk",
		"Preah Vihear",
		"Prey Veng",
		"Pursat",
		"Ratanakiri",
		"Siem Reap",
		"Stung Treng",
		"Svay Rieng",
		"Takeo",
	),
	"Cameroon"=> array(
		"Adamawa",
		"Centre",
		"East",
		"Extreme North",
		"Littoral",
		"North",
		"Northwest",
		"West",
		"South",
		"SouthWest",
	),
	"Canada"=> array(
		"Alberta",
		"British Columbia",
		"Manitoba",
		"New Brunswick",
		"Newfoundland and Labrador",
		"Northwest Territories",
		"Nova Scotia",
		"Nunavut",
		"Ontario",
		"Prince Edward Island",
		"Québec",
		"Saskatchewan",
		"Yukon Territory",
	),
	"Cape Verde"=> array(
		"Boa Vista",
		"Brava",
		"Maio",
		"Mosteiros",
		"Paul",
		"Porto Novo",
		"Praia",
		"Ribeira Brava",
		"Ribeira Grande",
		"Ribeira Grande de Santiago",
		"Sal",
		"Santa Catarina",
		"Santa Catarina do Fogo",
		"Santa Cruz",
		"Sao Domingos",
		"Sao Filipe",
		"Sao Miguel",
		"Sao Salvador do Mundo",
		"Sao Vicente",
		"Tarrafal",
		"Tarrafal de Sao Nicolau",
	),
	"Cayman Islands"=> array(
		"George Town",
		"West Bay",
		"Bodden Town",
		"North Side",
		"East End",
		"Cayman Brac",
		"Little Cayman",
	),
	"Central African Republic"=> array(
		"Bamingui-Bangoran",
		"Bangui",
		"Basse-Kotto",
		"Cuvette-Ouest",
		"Haut-Mbomou",
		"Haute-Kotto",
		"Kemo",
		"Lobaye",
		"Mambere-Kadei",
		"Mbomou",
		"Nana-Grebizi",
		"Nana-Mambere",
		"Ombella-Mpoko",
		"Ouaka",
		"Ouham",
		"Ouham-Pende",
		"Sangha-Mbaere",
	),
	"Chad"=> array(
		"Batha",
		"Chari-Baguirmi",
		"Hadjer-Lamis",
		"Wadi Fira",
		"Bahr El Gazel",
		"Borkou",
		"Ennedi",
		"Guéra",
		"Kanem",
		"Lac",
		"Logone Occidental",
		"Logone Oriental",
		"Mandoul",
		"Mayo-Kebbi Est",
		"Mayo-Kebbi Ouest",
		"Moyen-Chari",
		"Ouaddaï",
		"Salamat",
		"Sila",
		"Tandjilé",
		"Tibesti",
		"N Djamena",
	),
	"Chile"=> array(
		"Aisen del General Carlos Ibanez del Campo",
		"Antofagasta",
		"Araucania",
		"Arica y Parinacota",
		"Atacama",
		"Bio-Bio",
		"Coquimbo",
		"Libertador General Bernardo O Higgins",
		"Los Lagos",
		"Los Rios",
		"Magallanes y de la Antartica Chilena",
		"Maule",
		"Region Metropolitana",
		"Tarapaca",
		"Valparaiso",
	),
	"China"=> array(
		"Anhui",
		"Beijing",
		"Chongqing",
		"Fujian",
		"Gansu",
		"Guangdong",
		"Guangxi",
		"Guizhou",
		"Hainan",
		"Hebei",
		"Heilongjiang",
		"Henan",
		"Hubei",
		"Hunan",
		"Jiangsu",
		"Jiangxi",
		"Jilin",
		"Liaoning",
		"Nei Mongol",
		"Ningxia",
		"Qinghai",
		"Shaanxi",
		"Shandong",
		"Shanghai",
		"Shanxi",
		"Sichuan",
		"Tianjin",
		"Xinjiang",
		"Xizang",
		"Yunnan",
		"Zhejiang",
	),
	"Colombia"=> array(
		"Amazonas",
		"Antioquia",
		"Arauca",
		"Atlantico",
		"Bolivar",
		"Boyaca",
		"Caldas",
		"Caqueta",
		"Casanare",
		"Cauca",
		"Cesar",
		"Choco",
		"Cordoba",
		"Cundinamarca",
		"Distrito Especial",
		"Guainia",
		"Guaviare",
		"Huila",
		"La Guajira",
		"Magdalena",
		"Meta",
		"Narino",
		"Norte de Santander",
		"Putumayo",
		"Quindio",
		"Risaralda",
		"San Andres y Providencia",
		"Santander",
		"Sucre",
		"Tolima",
		"Valle del Cauca",
		"Vaupes",
		"Vichada",
	),
	"Comoros"=> array(
		"Anjouan",
		"Grande Comore",
		"Moheli",
	),
	"Congo Brazzaville"=> array(
		"Bouenza",
		"Brazzaville",
		"Cuvette",
		"Cuvette-Ouest",
		"Kouilou",
		"Lekoumou",
		"Likouala",
		"Niari",
		"Plateaux",
		"Pool",
		"Republic of the Congo",
		"Sangha",
	),
	"Congo Kinshasa"=> array(
		"Bandundu",
		"Bas-Congo",
		"Equateur",
		"Kasai-Occidental",
		"Kasai-Oriental",
		"Katanga",
		"Kinshasa",
		"Maniema",
		"Nord-Kivu",
		"Orientale",
		"Sud-Kivu",
	),
	"Cook Islands"=> array(
		"Cook Islands",
	),
	"Costa Rica"=> array(
		"Alajuela",
		"Cartago",
		"Guanacaste",
		"Heredia",
		"Limon",
		"Puntarenas",
		"San Jose",
	),
	"Croatia"=> array(
		"Bjelovarsko-Bilogorska",
		"Brodsko-Posavska",
		"Dubrovacko-Neretvanska",
		"Grad Zagreb",
		"Istarska",
		"Karlovacka",
		"Koprivnicko-Krizevacka",
		"Krapinsko-Zagorska",
		"Licko-Senjska",
		"Medimurska",
		"Osjecko-Baranjska",
		"Pozesko-Slavonska",
		"Primorsko-Goranska",
		"Sibensko-Kninska",
		"Sisacko-Moslavacka",
		"Splitsko-Dalmatinska",
		"Varazdinska",
		"Viroviticko-Podravska",
		"Vukovarsko-Srijemska",
		"Zadarska",
		"Zagrebacka",
	),
	"Cuba"=> array(
		"Artemisa",
		"Camaguey",
		"Ciego de Avila",
		"Cienfuegos",
		"Ciudad de la Habana",
		"Granma",
		"Guantanamo",
		"Holguin",
		"Isla de la Juventud",
		"La Habana",
		"Las Tunas",
		"Matanzas",
		"Mayabeque",
		"Pinar del Rio",
		"Sancti Spiritus",
		"Santiago de Cuba",
		"Villa Clara",
	),
	"Curacao"=> array(
		"Curacao",
	),
	"Cyprus"=> array(
		"Famagusta",
		"Kyrenia",
		"Larnaca",
		"Limassol",
		"Nicosia",
		"Paphos",
	),
	"Czech Republic"=> array(
		"Hlavni",
		"Jihocesky",
		"Jihomoravsky",
		"Karlovarsky",
		"Kralovehradecky",
		"Liberecky",
		"Moravskoslezsky",
		"Olomoucky",
		"Pardubicky",
		"Plzensky",
		"Stredocesky",
		"Ustecky",
		"Vysocina",
		"Zlinsky",
	),
	"Cote Ivoire"=> array(
		"Agneby",
		"Bafing",
		"Bas-Sassandra",
		"Denguele",
		"Dix-Huit Montagnes",
		"Fromager",
		"Haut-Sassandra",
		"Lacs",
		"Lagunes",
		"Marahoue",
		"Moyen-Cavally",
		"Moyen-Comoe",
		"N zi-Comoe",
		"Savanes",
		"Sud-Bandama",
		"Sud-Comoe",
		"Vallee du Bandama",
		"Worodougou",
		"Zanzan",
	),
	"Denmark"=> array(
		"Hovedstaden",
		"Midtjylland",
		"Nordjylland",
		"Sjelland",
		"Syddanmark",
	),
	"Djibouti"=> array(
		"Ali Sabieh",
		"Arta",
		"Dikhil",
		"Djibouti",
		"Obock",
		"Tadjoura",
	),
	"Dominica"=> array(
		"Saint Andrew",
		"Saint David",
		"Saint George",
		"Saint John",
		"Saint Joseph",
		"Saint Luke",
		"Saint Mark",
		"Saint Patrick",
		"Saint Paul",
		"Saint Peter",
	),
	"Dominican Republic"=> array(
		"Azua",
		"Baoruco",
		"Barahona",
		"Dajabon",
		"Distrito Nacional",
		"Duarte",
		"El Seibo",
		"Elias Pina",
		"Espaillat",
		"Hato Mayor",
		"Independencia",
		"La Altagracia",
		"La Romana",
		"La Vega",
		"Maria Trinidad Sanchez",
		"Monsenor Nouel",
		"Monte Cristi",
		"Monte Plata",
		"Pedernales",
		"Peravia",
		"Puerto Plata",
		"Salcedo",
		"Samana",
		"San Cristobal",
		"San Juan",
		"San Pedro De Macoris",
		"Sanchez Ramirez",
		"Santiago",
		"Santiago Rodriguez",
		"Valverde",
	),
	"Ecuador"=> array(
		"Azuay",
		"Bolivar",
		"Canar",
		"Carchi",
		"Chimborazo",
		"Cotopaxi",
		"El Oro",
		"Esmeraldas",
		"Galapagos",
		"Guayas",
		"Imbabura",
		"Loja",
		"Los Rios",
		"Manabi",
		"Morona-Santiago",
		"Napo",
		"Orellana",
		"Pastaza",
		"Pichincha",
		"Santa Elena",
		"Sucumbios",
		"Tungurahua",
		"Zamora-Chinchipe",
	),
	"Egypt"=> array(
		"Ad Daqahliyah",
		"Al Bahr al Ahmar",
		"Al Buhayrah",
		"Al Fayyum",
		"Al Gharbiyah",
		"Al Iskandariyah",
		"Al Isma iliyah",
		"Al Jizah",
		"Al Minufiyah",
		"Al Minya",
		"Al Qahirah",
		"Al Qalyubiyah",
		"Al Wadi al Jadid",
		"As Suways",
		"Ash Sharqiyah",
		"Aswan",
		"Asyut",
		"Bani Suwayf",
		"Bur Sa id",
		"Dumyat",
		"Janub Sina",
		"Kafr ash Shaykh",
		"Matruh",
		"Muhafazat al Uqsur",
		"Qina",
		"Shamal Sina",
		"Suhaj",
	),
	"El Salvador"=> array(
		"Ahuachapan",
		"Cabanas",
		"Chalatenango",
		"Cuscatlan",
		"La Libertad",
		"La Paz",
		"La Union",
		"Morazan",
		"San Miguel",
		"San Salvador",
		"San Vicente",
		"Santa Ana",
		"Sonsonate",
		"Usulutan",
	),
	"Equatorial Guinea"=> array(
		"Annobon",
		"Bioko Norte",
		"Bioko Sur",
		"Centro Sur",
		"Kie-Ntem",
		"Litoral",
		"Wele-Nzas",
	),
	"Eritrea"=> array(
		"Anseba",
		"Central",
		"Gash Barka",
		"Northern Red Sea",
		"Southern",
		"Southern Red Sea",
	),
	"Estonia"=> array(
		"Harjumaa",
		"Hiiumaa",
		"Ida-Virumaa",
		"Jarvamaa",
		"Jogevamaa",
		"Laane-Virumaa",
		"Laanemaa",
		"Parnumaa",
		"Polvamaa",
		"Raplamaa",
		"Saaremaa",
		"Tartumaa",
		"Valgamaa",
		"Viljandimaa",
		"Vorumaa",
	),
	"Ethiopia"=> array(
		"Adis Abeba",
		"Afar",
		"Amara",
		"Binshangul Gumuz",
		"Dire Dawa",
		"Gambela Hizboch",
		"Hareri Hizb",
		"Oromiya",
		"Sumale",
		"Tigray",
	),
	"Faroe Islands"=> array(
		"Eysturoy",
		"Nordoyar",
		"Sandoy",
		"Streymoy",
		"Suduroy",
		"Vagar",
	),
	"Figi"=> array(
		"Central",
		"Eastern",
		"Northern",
		"Western",
	),
	"Finland"=> array(
		"Central Finland",
		"Central Ostrobothnia",
		"Finland Proper",
		"Kainuu",
		"Kymenlaakso",
		"Lapland",
		"North Karelia",
		"Northern Ostrobothnia",
		"Northern Savonia",
		"Ostrobothnia",
		"Paijat-Hame",
		"Pirkanmaa",
		"Satakunta",
		"South Karelia",
		"Southern Ostrobothnia",
		"Southern Savonia",
		"Tavastia Proper",
		"Uusimaa",
	),
	"France"=> array(
		"Alpes Cote d Azur",
		"Alsace",
		"Aquitaine",
		"Auvergne",
		"Basse-Normandie",
		"Bourgogne",
		"Bretagne or Brittany",
		"Centre",
		"Champagne-Ardenne",
		"Corsica or Corse",
		"Franche-Comte",
		"Haute-Normandie",
		"Ile-De-France",
		"Midi-Pyrenees",
		"Nord-Pas-de-Calais",
		"Languedoc-Roussillon",
		"Limousin",
		"Lorraine",
		"Picardie",
		"Pays de la Loire",
		"Poitou-Charentes",
		"Rhone-Alpes",
	),
	"Gabon"=> array(
		"Estuaire",
		"Haut-Ogooue",
		"Moyen-Ogooue",
		"Ngounie",
		"Nyanga",
		"Ogooue-Ivindo",
		"Ogooue-Lolo",
		"Ogooue-Maritime",
		"Woleu-Ntem",
	),
	"Gambia"=> array(
		"Banjul",
		"Central River",
		"Lower River",
		"North Bank",
		"Upper River",
		"Western",
	),
	"Georgia"=> array(
		"Abkhazia",
		"Ajaria",
		"Akhalk alak is Raioni",
		"Baghdat is Raioni",
		"Borjomis Raioni",
		"Goris Raioni",
		"Guria",
		"Imereti",
		"Javis Raioni",
		"K arelis Raioni",
		"Kakheti",
		"Khashuris Raioni",
		"Kvemo Kartli",
		"Mtskheta-Mtianeti",
		"Racha-Lechkhumi and Kvemo Svaneti",
		"Samegrelo and Zemo Svaneti",
		"Samtskhe-Javakheti",
		"Shida Kartli",
		"T bilisi",
		"Vanis Raioni",
	),
	"Germany"=> array(
		"Baden-Wurttemberg",
		"Bayern",
		"Berlin",
		"Brandenburg",
		"Bremen",
		"Hamburg",
		"Hessen",
		"Mecklenburg-Vorpommern",
		"Niedersachsen",
		"Nordrhein-Westfalen",
		"Rheinland-Pfalz",
		"Saarland",
		"Sachsen",
		"Sachsen-Anhalt",
		"Schleswig-Holstein",
		"Thuringen",
	),
	"Ghana"=> array(
		"Ashanti",
		"Brong-Ahafo",
		"Central",
		"Eastern",
		"Greater Accra",
		"Northern",
		"Upper East",
		"Upper West",
		"Volta",
		"Western",
	),
	"Gibraltar"=> array(
		"Gibraltar",
	),
	"Greece"=> array(
		"Aitolia kai Akarnania",
		"Akhaia",
		"Argolis",
		"Arkadhia",
		"Arta",
		"Attiki",
		"Dhodhekanisos",
		"Drama",
		"Evritania",
		"Evros",
		"Evvoia",
		"Florina",
		"Fokis",
		"Fthiotis",
		"Grevena",
		"Ilia",
		"Imathia",
		"Ioannina",
		"Iraklion",
		"Kardhitsa",
		"Kastoria",
		"Kavala",
		"Kefallinia",
		"Kerkira",
		"Khalkidhiki",
		"Khania",
		"Khios",
		"Kikladhes",
		"Kilkis",
		"Korinthia",
		"Kozani",
		"Lakonia",
		"Larisa",
		"Lasithi",
		"Lesvos",
		"Levkas",
		"Magnisia",
		"Messinia",
		"Pella",
		"Pieria",
		"Preveza",
		"Rethimni",
		"Rodhopi",
		"Samos",
		"Serrai",
		"Thesprotia",
		"Thessaloniki",
		"Trikala",
		"Voiotia",
		"Xanthi",
		"Zakinthos",
	),
	"Greenland"=> array(
		"Kujalleq",
		"Qaasuitsup",
		"Qeqqata",
		"Sermersooq",
		"Vestgronland",
	),
	"Grenada"=> array(
		"Saint Andrew",
		"Saint David",
		"Saint George",
		"Saint John",
		"Saint Mark",
		"Saint Patrick",
	),
	"Guadeloupe"=> array(
		"Guadeloupe",
	),
	"Guam"=> array(
		"Agana Heights",
		"Agat",
		"Asan-Maina",
		"Barrigada",
		"Chalan Pago-Ordot",
		"Dededo",
		"Hagatna",
		"Inarajan",
		"Mangilao",
		"Merizo",
		"Mongmong-Toto-Maite",
		"Piti",
		"Santa Rita",
		"Sinajana",
		"Talofofo",
		"Tamuning-Tumon-Harmon",
		"Umatac",
		"Yigo",
		"Yona",
	),
	"Guatemala"=> array(
		"Alta Verapaz",
		"Baja Verapaz",
		"Chimaltenango",
		"Chiquimula",
		"El Progreso",
		"Escuintla",
		"Guatemala",
		"Huehuetenango",
		"Izabal",
		"Jalapa",
		"Jutiapa",
		"Peten",
		"Quetzaltenango",
		"Quiche",
		"Retalhuleu",
		"Sacatepequez",
		"San Marcos",
		"Santa Rosa",
		"Solola",
		"Suchitepequez",
		"Totonicapan",
		"Zacapa",
	),
	"Guernsey"=> array(
		"Guernsey",
	),
	"Guinea"=> array(
		"Beyla",
		"Boffa",
		"Boke",
		"Conakry",
		"Coyah",
		"Dabola",
		"Dalaba",
		"Dinguiraye",
		"Dubreka",
		"Faranah",
		"Forecariah",
		"Fria",
		"Gaoual",
		"Gueckedou",
		"Kankan",
		"Kerouane",
		"Kindia",
		"Kissidougou",
		"Koubia",
		"Koundara",
		"Kouroussa",
		"Labe",
		"Lelouma",
		"Lola",
		"Macenta",
		"Mali",
		"Mamou",
		"Mandiana",
		"Nzerekore",
		"Pita",
		"Siguiri",
		"Telimele",
		"Tougue",
		"Yomou",
	),
	"Guinea-Bissau"=> array(
		"Bafata",
		"Biombo",
		"Bissau",
		"Bolama",
		"Cacheu",
		"Gabu",
		"Oio",
		"Quinara",
		"Tombali",
	),
	"Guyana"=> array(
		"Cuyuni-Mazaruni",
		"Demerara-Mahaica",
		"East Berbice-Corentyne",
		"Essequibo Islands-West Demerara",
		"Mahaica-Berbice",
		"Pomeroon-Supenaam",
		"Upper Demerara-Berbice",
	),
	"Haiti"=> array(
		"Artibonite",
		"Centre",
		"Grand Anse",
		"Nippes",
		"Nord",
		"Nord-Est",
		"Nord-Ouest",
		"Ouest",
		"Sud",
		"Sud-Est",
	),
	"Honduras"=> array(
		"Atlantida",
		"Choluteca",
		"Colon",
		"Comayagua",
		"Copan",
		"Cortes",
		"El Paraiso",
		"Francisco Morazan",
		"Gracias a Dios",
		"Intibuca",
		"Islas de la Bahia",
		"La Paz",
		"Lempira",
		"Ocotepeque",
		"Olancho",
		"Santa Barbara",
		"Valle",
		"Yoro",
	),
	"Hong Kong"=> array(
		"New Territories",
		"Kowloon",
		"Hong Kong Island",
	),
	"Hungary"=> array(
		"Bacs-Kiskun",
		"Baranya",
		"Bekes",
		"Borsod-Abauj-Zemplen",
		"Budapest",
		"Csongrad",
		"Fejer",
		"Gyor-Moson-Sopron",
		"Hajdu-Bihar",
		"Heves",
		"Jasz-Nagykun-Szolnok",
		"Komarom-Esztergom",
		"Nograd",
		"Pest",
		"Somogy",
		"Szabolcs-Szatmar-Bereg",
		"Tolna",
		"Vas",
		"Veszprem",
		"Zala",
	),
	"Iceland"=> array(
		"Austurland",
		"Hofuoborgarsvaoio",
		"Norourland Eystra",
		"Norourland Vestra",
		"Suourland",
		"Suournes",
		"Vestfiroir",
		"Vesturland",
	),
	"India"=> array(
		"Andaman and Nicobar Islands",
		"Andhra Pradesh",
		"Arunachal Pradesh",
		"Assam",
		"Bihar",
		"Chandigarh",
		"Chhattisgarh",
		"Dadra and Nagar Haveli",
		"Daman and Diu",
		"Delhi",
		"Goa",
		"Gujarat",
		"Haryana",
		"Himachal Pradesh",
		"Jammu and Kashmir",
		"Jharkhand",
		"Karnataka",
		"Kerala",
		"Lakshadweep",
		"Madhya Pradesh",
		"Maharashtra",
		"Manipur",
		"Meghalaya",
		"Mizoram",
		"Nagaland",
		"Orissa",
		"Puducherry",
		"Punjab",
		"Rajasthan",
		"Sikkim",
		"Tamil Nadu",
		"Telangana",
		"Tripura",
		"Uttar Pradesh",
		"Uttarakhand",
		"West Bengal",
	),
	"Indonesia"=> array(
		"Aceh",
		"Bali",
		"Banten",
		"Bengkulu",
		"Gorontalo",
		"Irian Jaya Barat",
		"Jakarta Raya",
		"Jambi",
		"Jawa Barat",
		"Jawa Tengah",
		"Jawa Timur",
		"Kalimantan Barat",
		"Kalimantan Selatan",
		"Kalimantan Tengah",
		"Kalimantan Timur",
		"Kepulauan Bangka Belitung",
		"Kepulauan Riau",
		"Lampung",
		"Maluku",
		"Maluku Utara",
		"Nusa Tenggara Barat",
		"Nusa Tenggara Timur",
		"Papua",
		"Riau",
		"Sulawesi Barat",
		"Sulawesi Selatan",
		"Sulawesi Tengah",
		"Sulawesi Tenggara",
		"Sulawesi Utara",
		"Sumatera Barat",
		"Sumatera Selatan",
		"Sumatera Utara",
		"Yogyakarta",
	),
	"Iran Republic"=> array(
		"Alborz",
		"Ardabil",
		"Azarbayjan-e Sharqi",
		"Bakhtaran",
		"Bushehr",
		"Chahar Mahall va Bakhtiari",
		"Esfahan",
		"Fars",
		"Gilan",
		"Golestan",
		"Hamadan",
		"Hormozgan",
		"Ilam",
		"Kerman",
		"Khorasan-e Janubi",
		"Khorasan-e Razavi",
		"Khorasan-e Shemali",
		"Khuzestan",
		"Kohkiluyeh va Buyer Ahmadi",
		"Kordestan",
		"Lorestan",
		"Markazi",
		"Mazandaran",
		"Ostan-e Azarbayjan-e Gharbi",
		"Qazvin",
		"Qom",
		"Semnan",
		"Sistan va Baluchestan",
		"Tehran",
		"Yazd",
		"Zanjan",
	),
	"Iraq"=> array(
		"Al Anbar",
		"Al Basrah",
		"Al Muthanna",
		"Al Qadisiyah",
		"An Najaf",
		"Arbil",
		"As Sulaymaniyah",
		"At Ta mim",
		"Babil",
		"Baghdad",
		"Dahuk",
		"Dhi Qar",
		"Diyala",
		"Karbala",
		"Maysan",
		"Ninawa",
		"Salah ad Din",
		"Wasit",
	),
	"Ireland"=> array(
		"Carlow",
		"Cavan",
		"Clare",
		"Cork",
		"Donegal",
		"Dublin",
		"Dublin City",
		"Fingal",
		"Galway",
		"Kerry",
		"Kildare",
		"Kilkenny",
		"Laois",
		"Leitrim",
		"Limerick",
		"Longford",
		"Louth",
		"Mayo",
		"Meath",
		"Monaghan",
		"Offaly",
		"Roscommon",
		"Sligo",
		"South Dublin",
		"Tipperary",
		"Tipperary North Riding",
		"Waterford",
		"Westmeath",
		"Wexford",
		"Wicklow",
	),
	"Isle of Man"=> array(
		"Isle of Man",
	),
	"Israel"=> array(
		"HaDarom",
		"HaMerkaz",
		"HaZafon",
		"Hefa",
		"Tel Aviv",
		"Yerushalayim",
	),
	"Italy"=> array(
		"Abruzzi",
		"Basilicata",
		"Calabria",
		"Campania",
		"Emilia-Romagna",
		"Friuli-Venezia Giulia",
		"Lazio",
		"Liguria",
		"Lombardia",
		"Marche",
		"Molise",
		"Piemonte",
		"Puglia",
		"Sardegna",
		"Sicilia",
		"Toscana",
		"Trentino-Alto Adige",
		"Umbria",
		"Valle Aosta",
		"Veneto",
	),
	"Jamaica"=> array(
		"Clarendon",
		"Hanover",
		"Kingston",
		"Manchester",
		"Portland",
		"Saint Andrew",
		"Saint Ann",
		"Saint Catherine",
		"Saint Elizabeth",
		"Saint James",
		"Saint Mary",
		"Saint Thomas",
		"Trelawny",
		"Westmoreland",
	),
	"Japan"=> array(
		"Aichi",
		"Akita",
		"Aomori",
		"Chiba",
		"Ehime",
		"Fukui",
		"Fukuoka",
		"Fukushima",
		"Gifu",
		"Gumma",
		"Hiroshima",
		"Hokkaido",
		"Hyogo",
		"Ibaraki",
		"Ishikawa",
		"Iwate",
		"Kagawa",
		"Kagoshima",
		"Kanagawa",
		"Kochi",
		"Kumamoto",
		"Kyoto",
		"Mie",
		"Miyagi",
		"Miyazaki",
		"Nagano",
		"Nagasaki",
		"Nara",
		"Niigata",
		"Oita",
		"Okayama",
		"Okinawa",
		"Osaka",
		"Saga",
		"Saitama",
		"Shiga",
		"Shimane",
		"Shizuoka",
		"Tochigi",
		"Tokushima",
		"Tokyo",
		"Tottori",
		"Toyama",
		"Wakayama",
		"Yamagata",
		"Yamaguchi",
		"Yamanashi",
	),
	"Jersey"=> array(
		"Jersey",
	),
	"Jordan"=> array(
		"Amman",
		"Al Aqabah",
		"Al Balqa",
		"Al Karak",
		"Al Mafraq",
		"At Tafilah",
		"Az Zarqa",
		"Irbid",
		"Ma an",
		"Madaba",
	),
	"Kazakhstan"=> array(
		"Almaty",
		"Almaty City",
		"Aqmola",
		"Aqtobe",
		"Astana",
		"Atyrau",
		"Bayqonyr",
		"East Kazakhstan",
		"Mangghystau",
		"North Kazakhstan",
		"Pavlodar",
		"Qaraghandy",
		"Qostanay",
		"Qyzylorda",
		"South Kazakhstan",
		"West Kazakhstan",
		"Zhambyl",
	),
	"Kenya"=> array(
		"Central",
		"Coast",
		"Eastern",
		"Nairobi Area",
		"North-Eastern",
		"Nyanza",
		"Rift Valley",
		"Western",
	),
	"Kiribati"=> array(
		"Gilbert Islands",
		"Line Islands",
	),
	"Korea Republic"=> array(
		"Chagang-do",
		"Hamgyong-bukto",
		"Hamgyong-namdo",
		"Hwanghae-bukto",
		"Hwanghae-namdo",
		"Kangwon-do",
		"Najin Sonbong-si",
		"P yongan-bukto",
		"P yongan-namdo",
		"P yongyang-si",
		"Yanggang-do",
		"Ch ungch ong-bukto",
		"Ch ungch ong-namdo",
		"Cheju-do",
		"Cholla-bukto",
		"Cholla-namdo",
		"Inch on-jikhalsi",
		"Kangwon-do",
		"Kwangju-jikhalsi",
		"Kyonggi-do",
		"Kyongsang-bukto",
		"Kyongsang-namdo",
		"Pusan-jikhalsi",
		"Seoul-t ukpyolsi",
		"Taegu-jikhalsi",
		"Taejon-jikhalsi",
		"Ulsan-gwangyoksi",
	),
	"Kuwait"=> array(
		"Al Ahmadi",
		"Al Asimah",
		"Al Farwaniyah",
		"Al Jahra",
		"Hawalli",
		"Mubarak al Kabir",
	),
	"Kyrgyzstan"=> array(
		"Batken",
		"Bishkek",
		"Chuy",
		"Jalal-Abad",
		"Naryn",
		"Osh",
		"Talas",
		"Ysyk-Kol",
	),
	"Lao"=> array(
		"Attapu",
		"Bokeo",
		"Bolikhamxai",
		"Champasak",
		"Houaphan",
		"Kampheng Nakhon Viangchan",
		"Khoueng Khammouan",
		"Khoueng Phongsali",
		"Khoueng Salavan",
		"Khoueng Savannakhet",
		"Khoueng Viangchan",
		"Khoueng Xekong",
		"Louangphrabang",
		"Loungnamtha",
		"Oudomxai",
		"Xaignabouri",
		"Xiangkhoang",
	),
	"Latvia"=> array(
		"Adazu",
		"Aglonas",
		"Aizkraukles",
		"Aizputes",
		"Alojas",
		"Aluksnes",
		"Babites",
		"Baltinavas",
		"Balvu",
		"Bauskas",
		"Beverinas",
		"Brocenu",
		"Carnikavas",
		"Cesu",
		"Cesvaines",
		"Ciblas",
		"Daugavpils",
		"Dobeles",
		"Dundagas",
		"Gulbenes",
		"Iecavas",
		"Incukalna",
		"Jaunjelgavas",
		"Jaunpiebalgas",
		"Jaunpils",
		"Jekabpils",
		"Jelgava",
		"Jelgavas",
		"Jurmala",
		"Kekavas",
		"Kokneses",
		"Kraslavas",
		"Kuldigas",
		"Liepaja",
		"Liepajas",
		"Limbazu",
		"Lubanas",
		"Ludzas",
		"Madonas",
		"Malpils",
		"Ogres",
		"Olaines",
		"Ozolnieku",
		"Preilu",
		"Rezeknes",
		"Riga",
		"Rigas",
		"Rojas",
		"Ropazu",
		"Rugaju",
		"Rundales",
		"Salacgrivas",
		"Saldus",
		"Sejas",
		"Siguldas",
		"Skrundas",
		"Stopinu",
		"Strencu",
		"Talsu",
		"Tukuma",
		"Vainodes",
		"Valkas",
		"Valmieras",
		"Varkavas",
		"Vecumnieku",
		"Ventspils",
	),
	"Lebanon"=> array(
		"Aakk",
		"Baalbek-Hermel",
		"Beqaa",
		"Beyrouth",
		"Liban-Nord",
		"Liban-Sud",
		"Mont-Liban",
		"Nabatiye",
	),
	"Lesotho"=> array(
		"Berea",
		"Butha-Buthe",
		"Leribe",
		"Mafeteng",
		"Maseru",
		"Mohales Hoek",
		"Mokhotlong",
		"Qachas Nek",
		"Quthing",
		"Thaba-Tseka",
	),
	"Liberia"=> array(
		"Bomi",
		"Bong",
		"Gbarpolu",
		"Grand Bassa",
		"Grand Cape Mount",
		"Grand Gedeh",
		"Grand Kru",
		"Lofa",
		"Margibi",
		"Maryland",
		"Montserrado",
		"Nimba",
		"River Cess",
		"River Gee",
		"Sino",
	),
	"Libya"=> array(
		"Al Butnan",
		"Al Jabal al Akhdar",
		"Al Jabal al Gharbi",
		"Al Jifarah",
		"Al Jufrah",
		"Al Kufrah",
		"Al Marj",
		"Al Marqab",
		"Al Wahat",
		"An Nuqat al Khams",
		"Az Zawiyah",
		"Benghazi",
		"Darnah",
		"Ghat",
		"Misratah",
		"Murzuq",
		"Nalut",
		"Sabha",
		"Surt",
		"Tripoli",
		"Wadi al Hayat",
		"Wadi ash Shati",
	),
	"Liechtenstein"=> array(
		"Balzers",
		"Eschen",
		"Gamprin",
		"Mauren",
		"Planken",
		"Ruggell",
		"Schaan",
		"Schellenberg",
		"Triesen",
		"Triesenberg",
		"Vaduz",
	),
	"Lithuania"=> array(
		"Alytaus",
		"Kauno",
		"Klaipedos",
		"Marijampoles",
		"Panevezio",
		"Siauliu",
		"Taurages",
		"Telsiu",
		"Utenos",
		"Vilniaus",
	),
	"Luxembourg"=> array(
		"Diekirch",
		"Grevenmacher",
		"Luxembourg",
	),
	"Macao"=> array(
		"Macau",
	),
	"Macedonia"=> array(
		"Aracinovo",
		"Belcista",
		"Berovo",
		"Bistrica",
		"Bitola",
		"Blatec",
		"Bogdanci",
		"Bogomila",
		"Bogovinje",
		"Bosilovo",
		"Brvenica",
		"Capari",
		"Caska",
		"Cegrane",
		"Centar",
		"Centar Zupa",
		"Cesinovo",
		"Cucer-Sandevo",
		"Debar",
		"Delcevo",
		"Delogozdi",
		"Demir Hisar",
		"Demir Kapija",
		"Dobrusevo",
		"Dolna Banjica",
		"Dolneni",
		"Drugovo",
		"Dzepciste",
		"Gazi Baba",
		"Gevgelija",
		"Gostivar",
		"Gradsko",
		"Ilinden",
		"Jegunovce",
		"Kamenjane",
		"Karbinci",
		"Karpos",
		"Kavadarci",
		"Kicevo",
		"Kisela Voda",
		"Klecevce",
		"Kocani",
		"Konce",
		"Kondovo",
		"Kosel",
		"Kratovo",
		"Kriva Palanka",
		"Krivogastani",
		"Krusevo",
		"Kuklis",
		"Kukurecani",
		"Kumanovo",
		"Labunista",
		"Lipkovo",
		"Lozovo",
		"Lukovo",
		"Makedonska Kamenica",
		"Makedonski Brod",
		"Meseista",
		"Miravci",
		"Mogila",
		"Murtino",
		"Negotino",
		"Negotino-Polosko",
		"Novaci",
		"Novo Selo",
		"Oblesevo",
		"Ohrid",
		"Orasac",
		"Orizari",
		"Oslomej",
		"Pehcevo",
		"Petrovec",
		"Plasnica",
		"Podares",
		"Prilep",
		"Probistip",
		"Radovis",
		"Rankovce",
		"Resen",
		"Rosoman",
		"Rostusa",
		"Samokov",
		"Saraj",
		"Sipkovica",
		"Sopiste",
		"Sopotnica",
		"Srbinovo",
		"Star Dojran",
		"Staro Nagoricane",
		"Stip",
		"Struga",
		"Strumica",
		"Studenicani",
		"Suto Orizari",
		"Sveti Nikole",
		"Tearce",
		"Tetovo",
		"Topolcani",
		"Valandovo",
		"Vasilevo",
		"Veles",
		"Velesta",
		"Vevcani",
		"Vinica",
		"Vranestica",
		"Vrapciste",
		"Vratnica",
		"Vrutok",
		"Zajas",
		"Zelenikovo",
		"Zelino",
		"Zitose",
		"Zletovo",
		"Zrnovci",
	),
	"Madagascar"=> array(
		"Alaotra-Mangoro",
		"Amoroni Mania",
		"Analamanga",
		"Analanjirofo",
		"Androy",
		"Anosy",
		"Atsimo-Andrefana",
		"Atsimo-Atsinanana",
		"Atsinanana",
		"Betsiboka",
		"Boeny",
		"Bongolava",
		"Diana",
		"Haute Matsiatra",
		"Ihorombe",
		"Itasy",
		"Melaky",
		"Menabe",
		"Sava",
		"Sofia",
		"Vakinankaratra",
		"Vatoavavy-Fitovinany",
	),
	"Malawi"=> array(
		"Balaka",
		"Blantyre",
		"Chikwawa",
		"Chiradzulu",
		"Chitipa",
		"Dedza",
		"Dowa",
		"Karonga",
		"Kasungu",
		"Likoma",
		"Lilongwe",
		"Machinga",
		"Mangochi",
		"Mchinji",
		"Mulanje",
		"Mwanza",
		"Mzimba",
		"Neno",
		"Nkhata Bay",
		"Nkhotakota",
		"Nsanje",
		"Ntcheu",
		"Ntchisi",
		"Phalombe",
		"Rumphi",
		"Salima",
		"Thyolo",
		"Zomba",
	),
	"Malaysia"=> array(
		"Johor",
		"Kedah",
		"Kelantan",
		"Kuala Lumpur",
		"Labuan",
		"Melaka",
		"Negeri Sembilan",
		"Pahang",
		"Perak",
		"Perlis",
		"Pulau Pinang",
		"Putrajaya",
		"Sabah",
		"Sarawak",
		"Selangor",
		"Terengganu",
	),
	"Maladives"=> array(
		"Alifu",
		"Baa",
		"Dhaalu",
		"Gaafu Dhaalu",
		"Haa Alifu",
		"Haa Dhaalu",
		"Kaafu",
		"Laamu",
		"Maale",
		"Meemu",
		"Noonu",
		"Raa",
		"Seenu",
		"Shaviyani",
		"Thaa",
	),
	"Mali"=> array(
		"Bamako",
		"Gao",
		"Kayes",
		"Kidal",
		"Koulikoro",
		"Mopti",
		"Segou",
		"Sikasso",
		"Tombouctou",
	),
	"Marshall Islands"=> array(
		"Ailinglaplap Atoll",
		"Ailuk Atoll",
		"Arno Atoll",
		"Aur Atoll",
		"Ebon Atoll",
		"Enewetak Atoll",
		"Jabat Island",
		"Jaluit Atoll",
		"Kili Island",
		"Kwajalein Atoll",
		"Lae Atoll",
		"Lib Island",
		"Likiep Atoll",
		"Majuro Atoll",
		"Maloelap Atoll",
		"Mejit Island",
		"Mili Atoll",
		"Namdrik Atoll",
		"Namu Atoll",
		"Rongelap Atoll",
		"Ujae Atoll",
		"Utrik Atoll",
		"Wotho Atoll",
		"Wotje Atoll",
	),
	"Martinique"=> array(
		"Fort-de-France",
		"La Trinité",
		"Le Marin",
		"Saint-Pierre",
	),
	"Mauritania"=> array(
		"Adrar",
		"Assaba",
		"Brakna",
		"Dakhlet Nouadhibou",
		"Gorgol",
		"Guidimaka",
		"Hodh Ech Chargui",
		"Hodh El Gharbi",
		"Inchiri",
		"Nouakchott",
		"Tagant",
		"Tiris Zemmour",
		"Trarza",
	),
	"Mauritius"=> array(
		"Black River",
		"Flacq",
		"Grand Port",
		"Moka",
		"Pamplemousses",
		"Plaines Wilhems",
		"Port Louis",
		"Riviere du Rempart",
		"Savanne",
	),
	"Mayotte"=> array(
		"Acoua",
		"Bandraboua",
		"Bandrele",
		"Boueni",
		"Chiconi",
		"Chirongui",
		"Dzaoudzi",
		"Kani-Keli",
		"Koungou",
		"Mamoudzou",
		"Mtsamboro",
		"Ouangani",
		"Pamandzi",
		"Sada",
		"Tsingoni",
	),
	"Mexico"=> array(
		"Aguascalientes",
		"Baja California",
		"Baja California Sur",
		"Campeche",
		"Chiapas",
		"Chihuahua",
		"Coahuila de Zaragoza",
		"Colima",
		"Distrito Federal",
		"Durango",
		"Guanajuato",
		"Guerrero",
		"Hidalgo",
		"Jalisco",
		"Mexico",
		"Michoacan de Ocampo",
		"Morelos",
		"Nayarit",
		"Nuevo Leon",
		"Oaxaca",
		"Puebla",
		"Queretaro de Arteaga",
		"Quintana Roo",
		"San Luis Potosi",
		"Sinaloa",
		"Sonora",
		"Tabasco",
		"Tamaulipas",
		"Tlaxcala",
		"Veracruz-Llave",
		"Yucatan",
		"Zacatecas",
	),
	"Micronesia"=> array(
		"Chuuk",
		"Kosrae",
		"Pohnpei",
		"Yap",
	),
	"Moldova"=> array(
		"Anenii Noi",
		"Balti",
		"Basarabeasca",
		"Bender",
		"Briceni",
		"Cahul",
		"Calarasi",
		"Cantemir",
		"Causeni",
		"Chisinau",
		"Cimislia",
		"Criuleni",
		"Donduseni",
		"Drochia",
		"Dubasari",
		"Edinet",
		"Falesti",
		"Floresti",
		"Gagauzia",
		"Glodeni",
		"Hincesti",
		"Ialoveni",
		"Leova",
		"Nisporeni",
		"Ocnita",
		"Orhei",
		"Rezina",
		"Riscani",
		"Singerei",
		"Soldanesti",
		"Soroca",
		"Stefan-Voda",
		"Stinga Nistrului",
		"Straseni",
		"Taraclia",
		"Telenesti",
		"Ungheni",
	),
	"Monaco"=> array(
		"Fontvieille",
		"Monaco-Ville",
		"Moneghetti",
		"Monte-Carlo",
		"The Condamine",
	),
	"Mongolia"=> array(
		"Arhangay",
		"Bayan-Olgiy",
		"Bayanhongor",
		"Bulgan",
		"Darhan-Uul",
		"Dornod",
		"Dornogovi",
		"Dundgovi",
		"Dzavhan",
		"Govi-Altay",
		"Govisumber",
		"Khentii",
		"Khovd",
		"Khovsgol",
		"Omnogovi",
		"Orhon",
		"Ovorhangay",
		"Selenge",
		"Suhbaatar",
		"Tov",
		"Ulaanbaatar",
		"Uvs",
	),
	"Montenegro"=> array(
		"Bar",
		"Budva",
		"Cetinje",
		"Danilovgrad",
		"Herceg Novi",
		"Kolasin",
		"Kotor",
		"Mojkovac",
		"Niksic",
		"Podgorica",
		"Tivat",
		"Ulcinj",
		"Zabljak",
	),
	"Montserrat"=> array(
		"Brades",
		"Davi Hill",
		"Drummonds",
		"Look Out",
		"Olveston",
		"Plymouth",
		"St. Peters",
		"Salem",
	),
	"Morocco"=> array(
		"Chaouia-Ouardigha",
		"Doukkala-Abda",
		"Fès-Boulemane",
		"Gharb-Chrarda-Béni Hssen",
		"Grand Casablanca",
		"Guelmim-Es Smara",
		"Marrakech-Tensift-El Haouz",
		"Meknès-Tafilalet",
		"Oriental",
		"Oued Ed-Dahab-Lagouira",
		"Laâyoune-Bonjdour-Sakia El Hamra",
		"Rabat-Salé-Zemmour-Zaer",
		"Souss-Massa-Drâa",
		"Tadla-Azilal",
		"Tangier-Taounate",
		"Taza-Al Hoceima-Taounate",
	),
	"Mozambique"=> array(
		"Cabo Delgado",
		"Gaza",
		"Inhambane",
		"Manica",
		"Maputo",
		"Nampula",
		"Niassa",
		"Sofala",
		"Tete",
		"Zambezia",
	),
	"Myanmar"=> array(
		"Chin",
		"Irrawaddy",
		"Kachin",
		"Karan",
		"Kayah",
		"Magwe",
		"Mandalay",
		"Mon",
		"Pegu",
		"Rakhine",
		"Sagaing",
		"Shan",
		"Tenasserim",
		"Yangon",
	),
	"Namibia"=> array(
		"Erongo",
		"Hardap",
		"Karas",
		"Kavango East",
		"Kavango West",
		"Khomas",
		"Kunene",
		"Ohangwena",
		"Omaheke",
		"Omusati",
		"Oshana",
		"Oshikoto",
		"Otjozondjupa",
		"Zambezi",
	),
	"Nauru"=> array(
		"Aiwo",
		"Anabar",
		"Anetan",
		"Anibare",
		"Baiti",
		"Boe",
		"Buada",
		"Denigomodu",
		"Ewa",
		"Ijuw",
		"Meneng",
		"Nibok",
		"Uaboe",
		"Yaren",
	),
	"Nepal"=> array(
		"Bagmati",
		"Bheri",
		"Dhawalagiri",
		"Gandaki",
		"Janakpur",
		"Karnali",
		"Kosi",
		"Lumbini",
		"Mahakali",
		"Mechi",
		"Narayani",
		"Rapti",
		"Sagarmatha",
		"Seti",
	),
	"Netherlands"=> array(
		"Drenthe",
		"Flevoland",
		"Friesland",
		"Gelderland",
		"Groningen",
		"Limburg",
		"Noord-Brabant",
		"Noord-Holland",
		"Overijssel",
		"Utrecht",
		"Zeeland",
		"Zuid-Holland",
	),
	"New Caledonia"=> array(
		"Belep",
		"Bouloupari",
		"Bourail",
		"Canala",
		"Dumbéa",
		"Farino",
		"Hienghène",
		"Houaïlou",
		"Kaala-Gomen",
		"Koné",
		"Kouaoua",
		"Koumac",
		"Île-des-Pins",
		"La Foa",
		"Le Mont-Dore",
		"Lifou",
		"Maré",
		"Moindou",
		"Nouméa",
		"Ouégoa",
		"Ouvéa",
		"Païta",
		"Poindimié",
		"Ponérihouen",
		"Pouébo",
		"Pouembout",
		"Poum",
		"Poya",
		"Sarraméa",
		"Thio",
		"Touho",
		"Voh",
		"Yaté",
	),
	"New Zealand"=> array(
		"Auckland",
		"Bay of Plenty",
		"Canterbury",
		"Gisborne",
		"Hawkes Bay",
		"Manawatu",
		"Marlborough",
		"Northland",
		"Otago",
		"Southland",
		"Taranaki",
		"Tasman Nelson",
		"Waikato",
		"Wellington",
		"West Coast",
	),
	"Nicaragua"=> array(
		"Autonoma Atlantico Norte",
		"Autonoma Atlantico Sur",
		"Boaco",
		"Carazo",
		"Chinandega",
		"Chontales",
		"Esteli",
		"Granada",
		"Jinotega",
		"Leon",
		"Madriz",
		"Managua",
		"Masaya",
		"Matagalpa",
		"Nueva Segovia",
		"Rio San Juan",
		"Rivas",
	),
	"Niger"=> array(
		"Agadez",
		"Diffa",
		"Dosso",
		"Maradi",
		"Niamey",
		"Tahoua",
		"Tillaberi",
		"Zinder",
	),
	"Nigeria"=> array(
		"Abia",
		"Adamawa",
		"Akwa Ibom",
		"Anambra",
		"Bauchi",
		"Bayelsa",
		"Benue",
		"Borno",
		"Cross River",
		"Delta",
		"Ebonyi",
		"Edo",
		"Ekiti",
		"Enugu",
		"Gombe",
		"Imo",
		"Jigawa",
		"Kaduna",
		"Kano",
		"Katsina",
		"Kebbi",
		"Kogi",
		"Kwara",
		"Lagos",
		"Nasarawa",
		"Niger",
		"Ogun",
		"Ondo",
		"Osun",
		"Oyo",
		"Plateau",
		"Rivers",
		"Sokoto",
		"Taraba",
		"Yobe",
		"Zamfara",
	),
	"Niue"=> array(
		"Alofi",
		"Avatele",
		"Hikutavake",
		"Lakepa",
		"Liku",
		"Mutalau",
	),
	"Norfolk Island"=> array(
		"Burnt Pine",
		"Cascade",
		"Kingston",
		"Nepean",
		"Philip Island",
	),
	"Northern Mariana Islands"=> array(
		"Alamagan",
		"Agrihan",
		"Aguijan",
		"Anatahan",
		"Asuncion Island",
		"Farallon de Medinilla",
		"Farallon de Pajaros",
		"Guam",
		"Guguan",
		"Maug Islands",
		"Pagan",
		"Rota",
		"Saipan",
		"Sarigan",
		"Tinian",
	),
	"Norway"=> array(
		"Akershus",
		"Aust-Agder",
		"Buskerud",
		"Finnmark",
		"Hedmark",
		"Hordaland",
		"More og Romsdal",
		"Nord-Trondelag",
		"Nordland",
		"Oppland",
		"Oslo",
		"Ostfold",
		"Rogaland",
		"Svalbard",
		"Sogn og Fjordane",
		"Sor-Trondelag",
		"Telemark",
		"Troms",
		"Vest-Agder",
		"Vestfold",
	),
	"Oman"=> array(
		"Ad Dakhiliyah",
		"Ad Dhahirah",
		"Al Batinah North",
		"Al Batinah South",
		"Al Buraimi",
		"Al Wusta",
		"Ash Sharqiyah North",
		"Ash Sharqiyah South",
		"Dhofar",
		"Masqat",
		"Musandam",
	),
	"Pakistan"=> array(
		"Azad Kashmir",
		"Balochistan",
		"Federally Administered Tribal Areas",
		"Gilgit-Baltistan",
		"Islamabad Capital Territory",
		"Khyber Pakhtunkhwa",
		"Punjab",
		"Sindh ",
	),
	"Palau"=> array(
		"Aimeliik",
		"Airai",
		"Angaur",
		"Hatohobei",
		"Kayangel",
		"Koror",
		"Melekeok",
		"Ngaraard",
		"Ngarchelong",
		"Ngardmau",
		"Ngaremlengui",
		"Ngatpang",
		"Ngchesar",
		"Ngiwal",
		"Peleliu",
		"Rock Islands",
		"Sonsorol",
	),
	"Palestinian"=> array(
		"Bethlehem",
		"Deir El Balah",
		"Gaza City",
		"Hebron",
		"Jenin",
		"Jericho",
		"Jerusalem",
		"Khan Yunis",
		"Nablus",
		"North Gaza",
		"Qaliqilya",
		"Rafah",
		"Ramallah and Al Bireh",
		"Salfit",
		"Tubas",
		"Tulkarm",
	),
	"Panama"=> array(
		"Bocas del Toro",
		"Chiriqui",
		"Coclé",
		"Colon",
		"Darién",
		"Herrera",
		"Los Santos",
		"Panama",
		"Panama East",
		"Veraguas",
	),
	"Papua New Guinea"=> array(
		"Autonomous Region of Bougainville",
		"Central",
		"Chimbu",
		"East New Britain",
		"East Sepik",
		"Eastern Highlands",
		"Enga",
		"Gulf",
		"Hela",
		"Jiwaka",
		"Madang",
		"Manus",
		"Milne Bay",
		"Morobe",
		"National Capital District",
		"New Ireland",
		"North Solomons",
		"Northern",
		"Sandaun",
		"Southern Highlands",
		"West New Britain",
		"Western",
		"Western Highlands",
	),
	"Paraguay"=> array(
		"Alto Paraguay",
		"Alto Parana",
		"Amambay",
		"Asuncion",
		"Boqueron",
		"Caaguazu",
		"Caazapa",
		"Canindeyu",
		"Central",
		"Concepcion",
		"Cordillera",
		"Distrito Capital",
		"Guaira",
		"Itapua",
		"Misiones",
		"Neembucu",
		"Paraguari",
		"Presidente Hayes",
		"San Pedro",
	),
	"Peru"=> array(
		"Amazonas",
		"Ancash",
		"Apurimac",
		"Arequipa",
		"Ayacucho",
		"Cajamarca",
		"Callao",
		"Cusco",
		"Huancavelica",
		"Huanuco",
		"Ica",
		"Junin",
		"La Libertad",
		"Lambayeque",
		"Lima",
		"Loreto",
		"Madre de Dios",
		"Moquegua",
		"Pasco",
		"Piura",
		"Puno",
		"San Martin",
		"Tacna",
		"Tumbes",
		"Ucayali",
	),
	"Philippines"=> array(
		"Autonomous",
		"Bicol",
		"Cagayan Valley",
		"Calabarzon",
		"Caraga",
		"Central Luzon",
		"Central Visayas",
		"Cordillera",
		"Davao",
		"Eastern Visayas",
		"Ilocos",
		"Mimaropa",
		"National Capital",
		"Northern Mindanao",
		"Soccsksargen",
		"Western Visayas",
		"Zamboanga Peninsula",
	),
	"Pitcairn"=> array(
		"Ducie Island",
		"Henderson Island",
		"Oeno Island",
		"Pitcairn Island",
		"Pitcairn Islands",
	),
	"Poland"=> array(
		"Dolnoslaskie",
		"Kujawsko-Pomorskie",
		"Lodzkie",
		"Lubelskie",
		"Lubuskie",
		"Malopolskie",
		"Opolskie",
		"Podkarpackie",
		"Podlaskie",
		"Pomorskie",
		"Slaskie",
		"Swietokrzyskie",
		"Warminsko-Mazurskie",
		"Wielkopolskie",
		"Zachodniopomorskie",
	),
	"Portugal"=> array(
		"Aveiro",
		"Azores",
		"Beja",
		"Braga",
		"Braganca",
		"Castelo Branco",
		"Coimbra",
		"Evora",
		"Faro",
		"Guarda",
		"Leiria",
		"Lisboa",
		"Madeira",
		"Portalegre",
		"Porto",
		"Santarem",
		"Setubal",
		"Viana do Castelo",
		"Vila Real",
		"Viseu",
	),
	"Puerto Rico"=> array(
		"Adjuntas",
		"Aguada",
		"Aguadilla",
		"Aguas Buenas",
		"Aibonito",
		"Anasco",
		"Arecibo",
		"Arroyo",
		"Barceloneta",
		"Barranquitas",
		"Bayamon",
		"Cabo Rojo",
		"Caguas",
		"Camuy",
		"Canovanas",
		"Carolina",
		"Catano",
		"Cayey",
		"Ceiba",
		"Ciales",
		"Cidra",
		"Coamo",
		"Comerio",
		"Corozal",
		"Culebra",
		"Dorado",
		"Fajardo",
		"Florida",
		"Guanica",
		"Guayama",
		"Guayanilla",
		"Guaynabo",
		"Gurabo",
		"Hatillo",
		"Hormigueros",
		"Humacao",
		"Isabela",
		"Juana Diaz",
		"Lajas",
		"Lares",
		"Las Marias",
		"Las Piedras",
		"Loiza",
		"Luquillo",
		"Manati",
		"Maricao",
		"Maunabo",
		"Mayaguez",
		"Moca",
		"Morovis",
		"Municipio de Jayuya",
		"Municipio de Juncos",
		"Naguabo",
		"Naranjito",
		"Patillas",
		"Penuelas",
		"Ponce",
		"Quebradillas",
		"Rincon",
		"Rio Grande",
		"Sabana Grande",
		"Salinas",
		"San German",
		"San Juan",
		"San Lorenzo",
		"San Sebastian",
		"Santa Isabel Municipio",
		"Toa Alta",
		"Toa Baja",
		"Trujillo Alto",
		"Utuado",
		"Vega Alta",
		"Vega Baja",
		"Vieques",
		"Villalba",
		"Yabucoa",
		"Yauco",
	),
	"Qatar"=> array(
		"Ad Dawhah",
		"Al Ghuwayriyah",
		"Al Jumayliyah",
		"Al Khawr",
		"Al Wakrah",
		"Ar Rayyan",
		"Ash Shamal",
		"Jarayan Al Batnah",
		"Umm Salal",
	),
	"Reunion"=> array(
		"Bras-Panon",
		"Cilaos",
		"Entre-Deux",
		"Étang-Salé",
		"La Plaine-des-Palmistes",
		"La Possession",
		"Le Port",
		"Le Tampon",
		"Les Avirons",
		"Petite-Île",
		"Saint-André",
		"Saint-Benoît",
		"Saint-Denis",
		"Saint-Joseph",
		"Saint-Leu",
		"Saint-Louis",
		"Sainte-Marie",
		"Saint-Paul",
		"Saint-Philippe",
		"Saint-Pierre",
		"Sainte-Suzanne",
		"Sainte-Rose",
		"Salazie",
		"Trois-Bassins",
	),
	"Romania"=> array(
		"Alba",
		"Arad",
		"Arges",
		"Bacau",
		"Bihor",
		"Bistrita-Nasaud",
		"Botosani",
		"Braila",
		"Brasov",
		"Bucuresti",
		"Buzau",
		"Calarasi",
		"Caras-Severin",
		"Cluj",
		"Constanta",
		"Covasna",
		"Dambovita",
		"Dolj",
		"Galati",
		"Giurgiu",
		"Gorj",
		"Harghita",
		"Hunedoara",
		"Ialomita",
		"Iasi",
		"Ilfov",
		"Maramures",
		"Mehedinti",
		"Mures",
		"Neamt",
		"Olt",
		"Prahova",
		"Salaj",
		"Satu Mare",
		"Sibiu",
		"Suceava",
		"Teleorman",
		"Timis",
		"Tulcea",
		"Valcea",
		"Vaslui",
		"Vrancea",
	),
	"Russian Federation"=> array(
		"Adygeya",
		"Altaisky krai",
		"Amur",
		"Arkhangelsk",
		"Astrakhan",
		"Bashkortostan",
		"Belgorod",
		"Bryansk",
		"Buryat",
		"Chechnya",
		"Chelyabinsk",
		"Chukot",
		"Chuvashia",
		"Dagestan",
		"Gorno-Altay",
		"Ingush",
		"Irkutsk",
		"Ivanovo",
		"Kabardin-Balkar",
		"Kaliningrad",
		"Kalmyk",
		"Kaluga",
		"Kamchatka",
		"Karachay-Cherkess",
		"Karelia",
		"Kemerovo",
		"Khabarovsk",
		"Khakass",
		"Khanty-Mansiy",
		"Kirov",
		"Komi",
		"Kostroma",
		"Krasnodar",
		"Krasnoyarskiy Kray",
		"Kurgan",
		"Kursk",
		"Leningrad",
		"Lipetsk",
		"Magadan",
		"Mariy-El",
		"Mordovia",
		"Moscow City",
		"Moskva",
		"Murmansk",
		"Nenets",
		"Nizhegorod",
		"North Ossetia",
		"Novgorod",
		"Novosibirsk",
		"Omsk",
		"Orel",
		"Orenburg",
		"Penza",
		"Perm",
		"Permskiy Kray",
		"Primor ye",
		"Pskov",
		"Rostov",
		"Ryazan",
		"Saint Petersburg City",
		"Sakha",
		"Sakhalin",
		"Samara",
		"Saratov",
		"Smolensk",
		"Stavropol",
		"Sverdlovsk",
		"Tambovskaya oblast",
		"Tatarstan",
		"Tomsk",
		"Tula",
		"Tuva",
		"Tver",
		"Tyumen",
		"Udmurt",
		"Ul yanovsk",
		"Vladimir",
		"Volgograd",
		"Vologda",
		"Voronezh",
		"Yamal-Nenets",
		"Yaroslavl",
		"Yevrey",
		"Zabaykalsky",
	),
	"Rwanda"=> array(
		"Butare",
		"Byumba",
		"Cyangugu",
		"Gikongoro",
		"Gisenyi",
		"Gitarama",
		"Kibungo",
		"Kibuye",
		"Kigali City",
		"Kigali Rural",
		"Ruhengeri",
		"Umutara",
	),
	"Saint Barthelemy"=> array(
		"Aéroport",
		"Anse des Cayes",
		"Anse des Lézards",
		"Anse du Gouverneur",
		"Anse du Grand Cul-de-Sac",
		"Barrière des Quatres Vents",
		"Camaruche",
		"Carénage",
		"Col de la Tourmente",
		"Colombier",
		"Corossol",
		"Devet",
		"Flamands",
		"Gouverneur",
		"Grand Cul-de-Sac",
		"Grand Fond",
		"Grande Saline",
		"Grande Vigie",
		"Gustavia",
		"La Grande Montagne",
		"La Pointe",
		"Le Château",
		"Le Palidor",
		"Lorient",
		"Lurin",
		"Marigot",
		"Merlette",
		"Mont Jean",
		"Morne Criquet",
		"Morne de Dépoudré",
		"Morne Rouge",
		"Petit Cul-de-Sac",
		"Petite Saline",
		"Pointe Milou",
		"Public",
		"Quartier du Roi",
		"Saint-Jean",
		"Terre Neuve",
		"Toiny",
		"Vitet",
	),
	"Saint Helena"=> array(
		"Alarm Forest",
		"Blue Hill",
		"Half Tree Hollow",
		"Jamestown",
		"Levelwood",
		"Longwood",
		"Sandy Bay",
		"St Pauls",
	),
	"Saint Kitts and Nevis"=> array(
		"Christ Church Nichola Town",
		"Saint Anne Sandy Point",
		"Saint George Basseterre",
		"Saint George Gingerland",
		"Saint James Windward",
		"Saint John Capesterre",
		"Saint John Figtree ",
		"Saint Mary Cayon",
		"Saint Paul Capesterre",
		"Saint Paul Charlestown",
		"Saint Peter Basseterre",
		"Saint Thomas Lowland",
		"Saint Thomas Middle Island",
		"Trinity Palmetto Point ",
	),
	"Saint Lucia"=> array(
		"Anse la Raye",
		"Canaries",
		"Castries",
		"Choiseul",
		"Dennery",
		"Forest Reserve",
		"Gros Islet",
		"Laborie",
		"Micoud",
		"Soufrière",
		"Vieux Fort",
	),
	"Saint-Martin"=> array(
		"Aerodrome de Lesperance",
		"Anse Marcel",
		"Baie de Grande Case",
		"Baie Longue",
		"Baie Rouge",
		"Colombier",
		"French Cul de Sac",
		"Friars Bay",
		"Lowlands",
		"Mount Fortune",
		"Orient Bay",
		"Oyster Pond",
		"Pinet Island",
		"Quartier d Orleans",
		"Rambaud",
		"Simpson Bay Lagoon",
		"Terres Basses",
	),
	"Saint Pierre and Miquelon"=> array(
		"Grande Miquelon",
		"Langlade",
		"Saint-Pierre",
	),
	"Saint Vincent and The Grenadines"=> array(
		"Ashton",
		"Calliaqua",
		"Canouan",
		"Chateaubelair",
		"Fancy",
		"Georgetown",
		"Kingstown",
		"Mustique",
		"Saint-Vincent ",
		"Union",
	),
	"Samoa"=> array(
		"A ana",
		"Aiga-i-le-Tai",
		"Atua",
		"Gaga emauga",
		"Gaga ifomauga",
		"Palauli",
		"Satupa itea",
		"Tuamasaga",
		"Va a-o-Fonoti",
		"Vaisigano",
	),
	"San Marino"=> array(
		"Acquaviva",
		"Borgo Maggiore",
		"Chiesanuova",
		"Domagnano",
		"Faetano",
		"Fiorentino",
		"Montegiardino",
		"San Marino",
		"Serravalle",
	),
	"Sao Tome and Principe"=> array(
		"Agua Grande",
		"Cantagalo",
		"Caué",
		"Lemba",
		"Lobata",
		"Mé-Zochi",
		"Pagué",
	),
	"Saudi Arabia"=> array(
		"Al Bahah",
		"Al Hudud ash Shamaliyah",
		"Al Jawf",
		"Al Madinah",
		"Al Qasim",
		"Ar Riyad",
		"Ash Sharqiyah",
		"Asir",
		"Ha il",
		"Jizan",
		"Makkah",
		"Najran",
		"Tabuk",
	),
	"Senegal"=> array(
		"Dakar",
		"Diourbel",
		"Fatick",
		"Kaffrine",
		"Kaolack",
		"Kedougou",
		"Kolda",
		"Louga",
		"Matam",
		"Saint-Louis",
		"Sedhiou",
		"Tambacounda",
		"Thies",
		"Ziguinchor",
	),
	"Serbia"=> array(
		"Backa",
		"Banat",
		"Branicevo",
		"Jablanica",
		"Kolubara",
		"Kosovo",
		"Macva",
		"Metohija",
		"Nisava",
		"Pcinja",
		"Pirot",
		"Pomoravlje",
		"Rasina",
		"Raska",
		"Rudnik",
		"Srem",
		"Stari Vlah",
		"Sumadija",
		"Timocka Krajina",
		"Toplica",
	),
	"Seychelles"=> array(
		"Anse aux Pins",
		"Anse Boileau",
		"Anse Etoile",
		"Anse Royal",
		"Au Cap",
		"Baie Lazare",
		"Baie Sainte Anne",
		"Beau Vallon",
		"Bel Air",
		"Bel Ombre",
		"Cascade",
		"English River",
		"Glacis",
		"Grand Anse",
		"Grand Anse Praslin",
		"La Digue and Inner Islands",
		"Les Mamelles",
		"Mahe Islands",
		"Mont Buxton",
		"Mont Fleuri",
		"Outer Islands",
		"Plaisance",
		"Pointe La Rue",
		"Port Glaud",
		"Praslin Islands",
		"Roche Caïman",
		"Saint Louis",
		"Takamaka",
	),
	"Sierra Leone"=> array(
		"Bo",
		"Bombali",
		"Bonthe",
		"Kailahun",
		"Kambia",
		"Kenema",
		"Koinadugu",
		"Kono",
		"Moyamba",
		"Port Loko",
		"Pujehun",
		"Tonkolili",
		"Western Area Rural",
		"Western Area Urban",
	),
	"Singapore"=> array(
		"Raffles Marina Park",
		"Anson",
		"Queenstown",
		"Telokh Balangah",
		"Pasir Panjang Clementi New Town",
		"High Street",
		"Middle Road",
		"Little India",
		"Orchard",
		"Bukit Timah Tanglin",
		"Watten Stae",
		"Toa Paoh",
		"Bradel",
		"Geylang",
		"Katok",
		"Bedok",
		"Loyang",
		"Tampines",
		"Serangoon Garden",
		"Ang mo Kio",
		"Upper Bukit Timah",
		"Jurong",
		"Bukit Panjang",
		"Tengah",
		"Woodlands",
		"Upper Thomson",
		"Yishun",
		"Seletar",
	),
	"Sint Maarten"=> array(
		"Cole Bay",
		"Copecoy",
		"Dawn Beach",
		"Fort Amsterdam",
		"Great Bay",
		"Guana Bay",
		"Koolbaai",
		"Mullet Bay",
		"Orange Grove",
		"Philipsburg",
		"Princes Quartier",
		"Simonbaai",
		"St Peters",
	),
	"Slovakia"=> array(
		"Banska Bystrica",
		"Bratislava",
		"Kosice",
		"Nitra",
		"Presov",
		"Trencin",
		"Trnava",
		"Zilina",
	),
	"Slovenia"=> array(
		"Goriska",
		"Gorenjska",
		"Jugovzhodna Slovenija",
		"Koroska",
		"Notranjsko-krasha",
		"Obalno-kraska",
		"Osrednjeslovenska",
		"Podravska",
		"Pomurska",
		"Savinjska",
		"Spodnjeposavska",
		"Zasavska",
	),
	"Solomon Islands"=> array(
		"Central",
		"Choiseul",
		"Guadalcanal",
		"Isabel",
		"Makira-Ulawa",
		"Malaita",
		"Rennell and Bellona",
		"Temotu",
		"Western",
	),
	"Somalia"=> array(
		"Awdal",
		"Bakool",
		"Banaadir",
		"Bari",
		"Bay",
		"Galguduud",
		"Gedo",
		"Hiiraan",
		"Jubbada Dhexe",
		"Jubbada Hoose",
		"Mudug",
		"Nugaal",
		"Sanaag",
		"Shabeellaha Dhexe",
		"Shabeellaha Hoose",
		"Sool",
		"Togdheer",
		"Woqooyi Galbeed",
	),
	"South Africa"=> array(
		"Eastern Cape",
		"Free State",
		"Gauteng",
		"KwaZulu-Natal",
		"Lesotho",
		"Limpopo",
		"Mpumalanga",
		"North-West",
		"Northern Cape",
		"Western Cape",
	),
	"South Georgia"=> array(
		"Bird Islands",
		"Bristol Islands",
		"Clerke Rocks",
		"Grytviken",
		"Montagu Islands",
		"Saunders Islands",
		"Southern Thule",
		"Traversay Islands",
	),
	"South Sudan"=> array(
		"Central Equatoria",
		"Eastern Equatoria",
		"Jonglei",
		"Lakes",
		"Northern Bahr el Ghazal",
		"Unity",
		"Upper Nile",
		"Warrap",
		"Western Bahr el Ghazal",
		"Western Equatoria",
	),
	"Spain"=> array(
		"Andalucia",
		"Aragon",
		"Asturias",
		"Ballearic Islands",
		"Basque Country",
		"Canary Islands",
		"Cantabria",
		"Castilla la Mancha",
		"Castille and Leon",
		"Catalonia",
		"Extremadura",
		"Galicia",
		"La Rioja",
		"Madrid",
		"Murcia",
		"Navarre",
		"Valencian Community",
	),
	"Sri Lanka"=> array(
		"Central",
		"Eastern",
		"North Central",
		"North Western",
		"Northern",
		"Sabaragamuwa",
		"Southern",
		"Uva",
		"Western",
	),
	"Sudan"=> array(
		"Al Jazirah",
		"Al Qadarif",
		"Blue Nile",
		"Central Darfur",
		"East Darfur",
		"Kassala",
		"Khartoum",
		"North Darfur",
		"North Kurdufan",
		"Northern",
		"Red Sea",
		"River Nile",
		"Sennar",
		"South Darfur",
		"South Krdufan",
		"West Darfur",
		"West Kurdufan",
		"White Nile",
	),
	"Suriname"=> array(
		"Brokopondo",
		"Commewijne",
		"Coronie",
		"Marowijne",
		"Nickerie",
		"Para",
		"Paramaribo",
		"Saramacca",
		"Sipaliwini",
		"Wanica",
	),
	"Svalbard and Jan Mayen"=> array(
		"Barentsburg",
		"Barentsoya",
		"Beerenberg",
		"Edgeoya",
		"Hopen",
		"Kong Karls Land",
		"Kvitoya",
		"Longyearbyen",
		"Nordaustlandet",
		"Ny-Alesund",
		"Prins Karls Forland",
		"Spitsbergen",
	),
	"Swaziland"=> array(
		"Hhohho",
		"Lubombo",
		"Manzini",
		"Shiselweni",
	),
	"Sweden"=> array(
		"Blekinge",
		"Dalarna",
		"Falkenberg Municipality",
		"Gavleborg",
		"Gotland",
		"Halmstad",
		"Hylte Municipality",
		"Jamtland",
		"Jonkoping",
		"Kalmar",
		"Krnoberg",
		"Kungsbacka",
		"Laholm Municipality",
		"Norbotten",
		"Orebro",
		"Ostergotland",
		"Skane",
		"Sodermanland",
		"Stockholm",
		"Uppsala",
		"Varberg",
		"Varmland",
		"Vasterbotten",
		"Vasternorrland",
		"Vastmanland",
		"Vastra Gotaland",
	),
	"Switzerland"=> array(
		"Aargau",
		"Ausser-Rhoden",
		"Basel-Landschaft",
		"Basel-Stadt",
		"Bern",
		"Fribourg",
		"Geneve",
		"Glarus",
		"Graubunden",
		"Inner-Rhoden",
		"Jura",
		"Luzern",
		"Neuchatel",
		"Nidwalden",
		"Obwalden",
		"Sankt Gallen",
		"Schaffhausen",
		"Schwyz",
		"Solothurn",
		"Thurgau",
		"Ticino",
		"Uri",
		"Valais",
		"Vaud",
		"Zug",
		"Zurich",
	),
	"Syrian Arab Republic"=> array(
		"Al Hasakah",
		"Al Ladhiqiyah",
		"Al Qunaytirah",
		"Ar Raqqah",
		"As Suwayda",
		"Dar",
		"Dayr az Zawr",
		"Dimashq",
		"Halab",
		"Hamah",
		"Hims",
		"Idlib",
		"Rif Dimashq",
		"Tartus",
	),
	"Taiwan"=> array(
		"Chaiyi",
		"Chunghua",
		"Hsinchu",
		"Hualien",
		"Ilan",
		"Kaohsiung",
		"Maoli",
		"Nantou",
		"Pingtung",
		"Taichung",
		"Tainan",
		"Taipei",
		"Taitung",
		"Taoyuan",
		"Yunlin",
	),
	"Tajikistan"=> array(
		"Dushanbe",
		"Gorno-Badakhshon",
		"Khatlon",
		"Regions of Republican Subordination",
		"Sughd",
	),
	"Tanzania"=> array(
		"Arusha",
		"Dar es Salaam",
		"Dodoma",
		"Iringa",
		"Kagera",
		"Kigoma",
		"Kilimanjaro",
		"Lindi",
		"Manyara",
		"Mara",
		"Mbeya",
		"Morogoro",
		"Mtwara",
		"Mwanza",
		"Pemba North",
		"Pemba South",
		"Pwani",
		"Rukwa",
		"Ruvuma",
		"Shinyanga",
		"Singida",
		"Tabora",
		"Tanga",
		"Zanzibar Central",
		"Zanzibar North",
		"Zanzibar Urban",
	),
	"Thailand"=> array(
		"Amnat Charoen",
		"Ang Thong",
		"Buriram",
		"Chachoengsao",
		"Chai Nat",
		"Chaiyaphum",
		"Chanthaburi",
		"Chiang Mai",
		"Chiang Rai",
		"Chon Buri",
		"Chumphon",
		"Kalasin",
		"Kamphaeng Phet",
		"Kanchanaburi",
		"Khon Kaen",
		"Krabi",
		"Krung Thep",
		"Lampang",
		"Lamphun",
		"Loei",
		"Lop Buri",
		"Mae Hong Son",
		"Maha Sarakham",
		"Mukdahan",
		"Nakhon Nayok",
		"Nakhon Pathom",
		"Nakhon Phanom",
		"Nakhon Ratchasima",
		"Nakhon Sawan",
		"Nakhon Si Thammarat",
		"Nan",
		"Narathiwat",
		"Nong Bua Lamphu",
		"Nong Khai",
		"Nonthaburi",
		"Pathum Thani",
		"Pattani",
		"Phangnga",
		"Phatthalung",
		"Phayao",
		"Phetchabun",
		"Phetchaburi",
		"Phichit",
		"Phitsanulok",
		"Phra Nakhon Si Ayutthaya",
		"Phrae",
		"Phuket",
		"Prachin Buri",
		"Prachuap Khiri Khan",
		"Ranong",
		"Ratchaburi",
		"Rayong",
		"Roi Et",
		"Sa Kaeo",
		"Sakon Nakhon",
		"Samut Prakan",
		"Samut Sakhon",
		"Samut Songkhram",
		"Saraburi",
		"Satun",
		"Sing Buri",
		"Sisaket",
		"Songkhla",
		"Sukhothai",
		"Suphan Buri",
		"Surat Thani",
		"Surin",
		"Tak",
		"Trang",
		"Trat",
		"Ubon Ratchathani",
		"Udon Thani",
		"Uthai Thani",
		"Uttaradit",
		"Yala",
		"Yasothon",
	),
	"Timor-Leste"=> array(
		"Baucau",
		"Dili",
		"Ermera",
		"Foho Tatarnailau",
		"Liquica",
		"Manatuto",
		"Pante Makasar",
		"Pulau Atauro",
		"Pulau Jaco",
		"Suai",
		"Tutuala",
	),
	"Togo"=> array(
		"Centrale",
		"Kara",
		"Maritime",
		"Plateaux",
		"Savanes",
	),
	"Tokelau"=> array(
		"Atafu",
		"Fakaofo",
		"Nukunonu",
	),
	"Tonga"=> array(
		"Ha apai Group",
		"Nelafu",
		"Niuafo ou",
		"Niuatoputapu",
		"Nuku alofa",
		"Tafahi",
		"Tongatapu Group",
		"Vava u Group",
	),
	"Trinidad and Tobago"=> array(
		"Arima",
		"Chaguanas",
		"Couva",
		"Diego Martin",
		"Eastern Tobago",
		"Mayaro",
		"Penal",
		"Point Fortin",
		"Port of Spain",
		"Princes Town",
		"San Juan",
		"Sangre Grande",
		"Scarborough",
		"Siparia",
	),
	"Tunisia"=> array(
		"Aiana",
		"Al Mahdia",
		"Al Munastir",
		"Bajah",
		"Ben Arous",
		"Bizerte",
		"El Kef",
		"Gabes",
		"Gafsa",
		"Jendouba",
		"Kairouan",
		"Kasserine",
		"Kebili",
		"Madanin",
		"Manouba",
		"Nabeul",
		"Sfax",
		"Sidi Bou Zid",
		"Siliana",
		"Sousse",
		"Tataouine",
		"Tozeur",
		"Tunis",
		"Zaghouan",
	),
	"Turkey"=> array(
		"Adana",
		"Adiyaman",
		"Afyonkarahisar",
		"Agri",
		"Aksaray",
		"Amasya",
		"Ankara",
		"Antalya",
		"Ardahan",
		"Artvin",
		"Aydin",
		"Balikesir",
		"Bartin",
		"Batman",
		"Bayburt",
		"Bilecik",
		"Bingol",
		"Bitlis",
		"Bolu",
		"Burdur",
		"Bursa",
		"Canakkale",
		"Cankiri",
		"Corum",
		"Denizli",
		"Diyarbakir",
		"Duzce",
		"Edirne",
		"Elazig",
		"Erzincan",
		"Erzurum",
		"Eskisehir",
		"Gaziantep",
		"Giresun",
		"Gumushane",
		"Hakkari",
		"Hatay",
		"Igdir",
		"Isparta",
		"Istanbul",
		"Izmir",
		"Kahramanmaras",
		"Karabuk",
		"Karaman",
		"Kars",
		"Kastamonu",
		"Kayseri",
		"Kilis",
		"Kirikkale",
		"Kirklareli",
		"Kirsehir",
		"Kocaeli",
		"Konya",
		"Kutahya",
		"Malatya",
		"Manisa",
		"Mardin",
		"Mersin",
		"Mugla",
		"Mus",
		"Nevsehir",
		"Nigde",
		"Ordu",
		"Osmaniye",
		"Rize",
		"Sakarya",
		"Samsun",
		"Sanliurfa",
		"Siirt",
		"Sinop",
		"Sirnak",
		"Sivas",
		"Tekirdag",
		"Tokat",
		"Trabzon",
		"Tunceli",
		"Usak",
		"Van",
		"Yalova",
		"Yozgat",
		"Zonguldak",
	),
	"Turkmenistan"=> array(
		"Ahal",
		"Balkan",
		"Dashoguz",
		"Lebap",
		"Mary",
	),
	"Turks and Caicos Islands"=> array(
		"Big Ambergris Cay",
		"Big Sand Cay",
		"Bush Cays",
		"Cotton Cay",
		"East Caicos",
		"East Cay",
		"Fish Cay",
		"French Cay",
		"Grand Turk",
		"Little Ambergris Cay",
		"Middle Caicos",
		"North Caicos",
		"Parrot Cay",
		"Pine Cay",
		"Providenciales ",
		"Salt Cay",
		"Seal Cays",
		"Six Hill Cays",
		"West Caicos",
		"West Sand Spit",
	),
	"Tuvalu"=> array(
		"Fanafuti",
		"Fongafale",
		"Nanumanga",
		"Nanumea",
		"Niulakita",
		"Niutao",
		"Nui",
		"Nukulaelae",
		"Nukufetau",
		"Vaitupu",
	),
	"Uganda"=> array(
		"Abim",
		"Adjumani",
		"Agago District",
		"Alebtong District",
		"Amolatar",
		"Amudat District",
		"Amuria",
		"Amuru",
		"Apac",
		"Arua",
		"Budaka",
		"Bududa",
		"Bugiri",
		"Buikwe District",
		"Bukedea",
		"Bukomansimbi District",
		"Bukwa",
		"Bulambuli District",
		"Bulisa",
		"Bundibugyo",
		"Bushenyi",
		"Busia",
		"Butaleja",
		"Buvuma District",
		"Buyende District",
		"Dokolo",
		"Gomba District",
		"Gulu",
		"Hoima",
		"Iganga",
		"Isingiro",
		"Jinja",
		"Kaabong",
		"Kabale",
		"Kabarole",
		"Kaberamaido",
		"Kalangala",
		"Kaliro",
		"Kampala",
		"Kampala District",
		"Kamuli",
		"Kamwenge",
		"Kanungu",
		"Kapchorwa",
		"Kasese",
		"Katakwi",
		"Kayunga",
		"Kibale",
		"Kiboga",
		"Kibuku District",
		"Kiryandongo District",
		"Kisoro",
		"Kitgum",
		"Koboko",
		"Kole District",
		"Kotido",
		"Kumi",
		"Kween District",
		"Kyankwanzi District",
		"Kyegegwa District",
		"Kyenjojo",
		"Lira",
		"Luuka District",
		"Luwero",
		"Lwengo District",
		"Lyantonde",
		"Manafwa",
		"Maracha",
		"Masaka",
		"Masindi",
		"Mayuge",
		"Mbale",
		"Mbarara",
		"Mitoma District",
		"Mityana",
		"Moroto",
		"Moyo",
		"Mpigi",
		"Mubende",
		"Mukono",
		"Nakapiripirit",
		"Nakaseke",
		"Nakasongola",
		"Namayingo District",
		"Namutumba",
		"Napak District",
		"Nebbi",
		"Ngora District",
		"Ntoroko District",
		"Ntungamo",
		"Otuke District",
		"Oyam",
		"Pader",
		"Pallisa",
		"Rakai",
		"Rubirizi District",
		"Rukungiri",
		"Sembabule",
		"Serere District",
		"Sheema District",
		"Sironko",
		"Soroti",
		"Tororo",
		"Wakiso",
		"Yumbe",
		"Zombo District",
	),
	"Ukraine"=> array(
		"Cherkas",
		"Chernihivs",
		"Chernivets",
		"Dnipropetrovs",
		"Donets",
		"Ivano-Frankivs",
		"Kharkivs",
		"Khersons",
		"Khmel nyts",
		"Kirovohrads",
		"Krym",
		"Kyyiv",
		"L vivs",
		"Luhans",
		"Mykolayivs",
		"Odes",
		"Poltavs",
		"Rivnens",
		"Sevastopol",
		"Sums",
		"Ternopils",
		"Vinnyts",
		"Volyns",
		"Zakarpats",
		"Zaporiz",
		"Zhytomyrs",
	),
	"United Arab Emirates"=> array(
		"Abu Dhabi",
		"Ajman",
		"Dubai",
		"Fujairah",
		"Ras Al Khaimah",
		"Sharjah",
		"Umm Al Quwain",
	),
	"United Kingdom"=> array(
		"East Midlands",
		"Easthern",
		"London",
		"North East",
		"North West",
		"Northern Ireland",
		"Scotland",
		"South East",
		"South West",
		"Wales",
		"West Midlands",
		"Yorkshire The Humber",
	),
	"United States"=> array(
		"Alabama",
		"Alaska",
		"Arizona",
		"Arkansas",
		"California",
		"Colorado",
		"Connecticut",
		"Delaware",
		"Florida",
		"Georgia",
		"Hawaii",
		"Idaho",
		"Illinois",
		"Indiana",
		"Iowa",
		"Kansas",
		"Kentucky",
		"Louisiana",
		"Maine",
		"Maryland",
		"Massachusetts",
		"Michigan",
		"Minnesota",
		"Mississippi",
		"Missouri",
		"Montana",
		"Nebraska",
		"Nevada",
		"New Hampshire",
		"New Jersey",
		"New Mexico",
		"New York",
		"North Carolina",
		"North Dakota",
		"Ohio",
		"Oklahoma",
		"Oregon",
		"Pennsylvania",
		"Rhode Island",
		"South Carolina",
		"South Dakota",
		"Tennessee",
		"Texas",
		"Utah",
		"Vermont",
		"Virginia",
		"Washington",
		"Washington dc",
		"West Virginia",
		"Wisconsin",
		"Wyoming",
	),
	"Uruguay"=> array(
		"Artigas",
		"Canelones",
		"Cerro Largo",
		"Colonia",
		"Durazno",
		"Flores",
		"Florida",
		"Lavalleja",
		"Maldonado",
		"Montevideo",
		"Paysandu",
		"Rio Negro",
		"Rivera",
		"Rocha",
		"Salto",
		"San Jose",
		"Soriano",
		"Tacuarembo",
		"Treinta y Tres",
	),
	"Uzbekistan"=> array(
		"Andijon",
		"Bukhoro",
		"Farghona",
		"Jizzax",
		"Khorazm",
		"Namangan",
		"Nawoiy",
		"Qashqadaryo",
		"Qoraqalpoghiston",
		"Samarqand",
		"Sirdaryo",
		"Surkhondaryo",
		"Toshkent",
		"Toshkent Shahri",
	),
	"Vanuatu"=> array(
		"Ambae",
		"Ambryn",
		"Efate",
		"Epi",
		"Erromango",
		"Espiritu Santo",
		"Futuna",
		"Malakula",
		"Pentecost",
		"Port Vila",
		"Tanna",
		"Torres Banks",
	),
	"Venezuela"=> array(
		"Amazonas",
		"Anzoategui",
		"Apure",
		"Aragua",
		"Barinas",
		"Bolivar",
		"Carabobo",
		"Cojedes",
		"Delta Amacuro",
		"Distrito Federal",
		"Falcon",
		"Guarico",
		"Lara",
		"Merida",
		"Miranda",
		"Monagas",
		"Nueva Esparta",
		"Portuguesa",
		"Sucre",
		"Tachira",
		"Trujillo",
		"Vargas",
		"Yaracuy",
		"Zulia",
	),
	"Vietnam"=> array(
		"An Giang",
		"Ba Ria-Vung Tau",
		"Ben Tre",
		"Binh Dinh",
		"Binh Thuan",
		"Can Tho",
		"Cao Bang",
		"Da Nang",
		"Dak Lak",
		"Dien Bien",
		"Dong Nai",
		"Dong Thap",
		"Ha Giang",
		"Ha Nam",
		"Ha Noi",
		"Ha Tay",
		"Ha Tinh",
		"Hai Duong",
		"Hai Phong",
		"Ho Chi Minh",
		"Hoa Binh",
		"Hung Yen",
		"Khanh Hoa",
		"Kien Giang",
		"Kon Tum",
		"Lai Chau",
		"Lam Dong",
		"Lang Son",
		"Lao Cai",
		"Long An",
		"Nam Dinh",
		"Nam Ha",
		"Nghe An",
		"Ninh Binh",
		"Ninh Thuan",
		"Phu Tho",
		"Phu Yen",
		"Quang Binh",
		"Quang Nam",
		"Quang Ngai",
		"Quang Ninh",
		"Quang Tri",
		"Soc Trang",
		"Son La",
		"Song Be",
		"Tay Ninh",
		"Thai Binh",
		"Thai Nguyen",
		"Thanh Hoa",
		"Thua Thien",
		"Tien Giang",
		"Tra Vinh",
		"Tuyen Quang",
		"Vinh Long",
		"Vinh Phu",
		"Vinh Puc Province",
	),
	"Wallis and Futuna"=> array(
		"Alofi Island",
		"Futuna Island",
		"Leava",
		"Mata-Utu",
		"Wallis Island",
	),
	"Western Sahara"=> array(
		"Ad Dakhla",
		"Aghwinit",
		"Al Haggounia",
		"Al Mahbas",
		"Amasine",
		"Argoub",
		"Bir Gandouz",
		"Bir Lahmar",
		"Boujdour",
		"Boukra",
		"Cnalwa",
		"Dawra",
		"Galtat Zemmour",
		"Jdiraiya",
		"Laayoune",
		"Mijek",
		"Nwayfadh",
		"Techla",
	),
	"Yemen"=> array(
		"Aden",
		"Aljanad",
		"Azal",
		"Hadramaut",
		"Sheba",
		"Tahama",
	),
	"Zambia"=> array(
		"Central",
		"Copperbelt",
		"Eastern",
		"Luapula",
		"Lusaka",
		"North-Western",
		"Northern",
		"Southern",
		"Western",
	),
	"Zimbabwe"=> array(
		"Bulawayo",
		"Harare",
		"Manicaland",
		"Mashonaland Central",
		"Mashonaland East",
		"Mashonaland West",
		"Masvingo",
		"Matabeleland North",
		"Matabeleland South",
		"Midlands",
	),
);
?>